// Code generated by NeverBlink protoc-java-fast. Do not edit!
package eu.neverblink.jelly.core.proto.v1;

import com.google.protobuf.DescriptorProtos;
import com.google.protobuf.Descriptors;
import java.util.Base64;

public final class Rdf {

    private static final byte[] descriptorData = Base64.getDecoder()
        .decode(
            "CglyZGYucHJvdG8SIWV1Lm9zdHJ6eWNpZWwuamVsbHkuY29yZS5wcm90by52MSI+CgZSZGZJcmkSGwoJ" +
            "cHJlZml4X2lkGAEgASgNUghwcmVmaXhJZBIXCgduYW1lX2lkGAIgASgNUgZuYW1lSWQiZwoKUmRmTGl0" +
            "ZXJhbBIQCgNsZXgYASABKAlSA2xleBIaCgdsYW5ndGFnGAIgASgJSABSB2xhbmd0YWcSHAoIZGF0YXR5" +
            "cGUYAyABKA1IAFIIZGF0YXR5cGVCDQoLbGl0ZXJhbEtpbmQiEQoPUmRmRGVmYXVsdEdyYXBoIqoGCglS" +
            "ZGZUcmlwbGUSQAoFc19pcmkYASABKAsyKS5ldS5vc3RyenljaWVsLmplbGx5LmNvcmUucHJvdG8udjEu" +
            "UmRmSXJpSABSBHNJcmkSGQoHc19ibm9kZRgCIAEoCUgAUgZzQm5vZGUSTAoJc19saXRlcmFsGAMgASgL" +
            "Mi0uZXUub3N0cnp5Y2llbC5qZWxseS5jb3JlLnByb3RvLnYxLlJkZkxpdGVyYWxIAFIIc0xpdGVyYWwS" +
            "UgoNc190cmlwbGVfdGVybRgEIAEoCzIsLmV1Lm9zdHJ6eWNpZWwuamVsbHkuY29yZS5wcm90by52MS5S" +
            "ZGZUcmlwbGVIAFILc1RyaXBsZVRlcm0SQAoFcF9pcmkYBSABKAsyKS5ldS5vc3RyenljaWVsLmplbGx5" +
            "LmNvcmUucHJvdG8udjEuUmRmSXJpSAFSBHBJcmkSGQoHcF9ibm9kZRgGIAEoCUgBUgZwQm5vZGUSTAoJ" +
            "cF9saXRlcmFsGAcgASgLMi0uZXUub3N0cnp5Y2llbC5qZWxseS5jb3JlLnByb3RvLnYxLlJkZkxpdGVy" +
            "YWxIAVIIcExpdGVyYWwSUgoNcF90cmlwbGVfdGVybRgIIAEoCzIsLmV1Lm9zdHJ6eWNpZWwuamVsbHku" +
            "Y29yZS5wcm90by52MS5SZGZUcmlwbGVIAVILcFRyaXBsZVRlcm0SQAoFb19pcmkYCSABKAsyKS5ldS5v" +
            "c3RyenljaWVsLmplbGx5LmNvcmUucHJvdG8udjEuUmRmSXJpSAJSBG9JcmkSGQoHb19ibm9kZRgKIAEo" +
            "CUgCUgZvQm5vZGUSTAoJb19saXRlcmFsGAsgASgLMi0uZXUub3N0cnp5Y2llbC5qZWxseS5jb3JlLnBy" +
            "b3RvLnYxLlJkZkxpdGVyYWxIAlIIb0xpdGVyYWwSUgoNb190cmlwbGVfdGVybRgMIAEoCzIsLmV1Lm9z" +
            "dHJ6eWNpZWwuamVsbHkuY29yZS5wcm90by52MS5SZGZUcmlwbGVIAlILb1RyaXBsZVRlcm1CCQoHc3Vi" +
            "amVjdEILCglwcmVkaWNhdGVCCAoGb2JqZWN0IroICgdSZGZRdWFkEkAKBXNfaXJpGAEgASgLMikuZXUu" +
            "b3N0cnp5Y2llbC5qZWxseS5jb3JlLnByb3RvLnYxLlJkZklyaUgAUgRzSXJpEhkKB3NfYm5vZGUYAiAB" +
            "KAlIAFIGc0Jub2RlEkwKCXNfbGl0ZXJhbBgDIAEoCzItLmV1Lm9zdHJ6eWNpZWwuamVsbHkuY29yZS5w" +
            "cm90by52MS5SZGZMaXRlcmFsSABSCHNMaXRlcmFsElIKDXNfdHJpcGxlX3Rlcm0YBCABKAsyLC5ldS5v" +
            "c3RyenljaWVsLmplbGx5LmNvcmUucHJvdG8udjEuUmRmVHJpcGxlSABSC3NUcmlwbGVUZXJtEkAKBXBf" +
            "aXJpGAUgASgLMikuZXUub3N0cnp5Y2llbC5qZWxseS5jb3JlLnByb3RvLnYxLlJkZklyaUgBUgRwSXJp" +
            "EhkKB3BfYm5vZGUYBiABKAlIAVIGcEJub2RlEkwKCXBfbGl0ZXJhbBgHIAEoCzItLmV1Lm9zdHJ6eWNp" +
            "ZWwuamVsbHkuY29yZS5wcm90by52MS5SZGZMaXRlcmFsSAFSCHBMaXRlcmFsElIKDXBfdHJpcGxlX3Rl" +
            "cm0YCCABKAsyLC5ldS5vc3RyenljaWVsLmplbGx5LmNvcmUucHJvdG8udjEuUmRmVHJpcGxlSAFSC3BU" +
            "cmlwbGVUZXJtEkAKBW9faXJpGAkgASgLMikuZXUub3N0cnp5Y2llbC5qZWxseS5jb3JlLnByb3RvLnYx" +
            "LlJkZklyaUgCUgRvSXJpEhkKB29fYm5vZGUYCiABKAlIAlIGb0Jub2RlEkwKCW9fbGl0ZXJhbBgLIAEo" +
            "CzItLmV1Lm9zdHJ6eWNpZWwuamVsbHkuY29yZS5wcm90by52MS5SZGZMaXRlcmFsSAJSCG9MaXRlcmFs" +
            "ElIKDW9fdHJpcGxlX3Rlcm0YDCABKAsyLC5ldS5vc3RyenljaWVsLmplbGx5LmNvcmUucHJvdG8udjEu" +
            "UmRmVHJpcGxlSAJSC29UcmlwbGVUZXJtEkAKBWdfaXJpGA0gASgLMikuZXUub3N0cnp5Y2llbC5qZWxs" +
            "eS5jb3JlLnByb3RvLnYxLlJkZklyaUgDUgRnSXJpEhkKB2dfYm5vZGUYDiABKAlIA1IGZ0Jub2RlElwK" +
            "D2dfZGVmYXVsdF9ncmFwaBgPIAEoCzIyLmV1Lm9zdHJ6eWNpZWwuamVsbHkuY29yZS5wcm90by52MS5S" +
            "ZGZEZWZhdWx0R3JhcGhIA1INZ0RlZmF1bHRHcmFwaBJMCglnX2xpdGVyYWwYECABKAsyLS5ldS5vc3Ry" +
            "enljaWVsLmplbGx5LmNvcmUucHJvdG8udjEuUmRmTGl0ZXJhbEgDUghnTGl0ZXJhbEIJCgdzdWJqZWN0" +
            "QgsKCXByZWRpY2F0ZUIICgZvYmplY3RCBwoFZ3JhcGgioQIKDVJkZkdyYXBoU3RhcnQSQAoFZ19pcmkY" +
            "ASABKAsyKS5ldS5vc3RyenljaWVsLmplbGx5LmNvcmUucHJvdG8udjEuUmRmSXJpSABSBGdJcmkSGQoH" +
            "Z19ibm9kZRgCIAEoCUgAUgZnQm5vZGUSXAoPZ19kZWZhdWx0X2dyYXBoGAMgASgLMjIuZXUub3N0cnp5" +
            "Y2llbC5qZWxseS5jb3JlLnByb3RvLnYxLlJkZkRlZmF1bHRHcmFwaEgAUg1nRGVmYXVsdEdyYXBoEkwK" +
            "CWdfbGl0ZXJhbBgEIAEoCzItLmV1Lm9zdHJ6eWNpZWwuamVsbHkuY29yZS5wcm90by52MS5SZGZMaXRl" +
            "cmFsSABSCGdMaXRlcmFsQgcKBWdyYXBoIg0KC1JkZkdyYXBoRW5kIm4KF1JkZk5hbWVzcGFjZURlY2xh" +
            "cmF0aW9uEhIKBG5hbWUYASABKAlSBG5hbWUSPwoFdmFsdWUYAiABKAsyKS5ldS5vc3RyenljaWVsLmpl" +
            "bGx5LmNvcmUucHJvdG8udjEuUmRmSXJpUgV2YWx1ZSI0CgxSZGZOYW1lRW50cnkSDgoCaWQYASABKA1S" +
            "AmlkEhQKBXZhbHVlGAIgASgJUgV2YWx1ZSI2Cg5SZGZQcmVmaXhFbnRyeRIOCgJpZBgBIAEoDVICaWQS" +
            "FAoFdmFsdWUYAiABKAlSBXZhbHVlIjgKEFJkZkRhdGF0eXBlRW50cnkSDgoCaWQYASABKA1SAmlkEhQK" +
            "BXZhbHVlGAIgASgJUgV2YWx1ZSLtAwoQUmRmU3RyZWFtT3B0aW9ucxIfCgtzdHJlYW1fbmFtZRgBIAEo" +
            "CVIKc3RyZWFtTmFtZRJaCg1waHlzaWNhbF90eXBlGAIgASgOMjUuZXUub3N0cnp5Y2llbC5qZWxseS5j" +
            "b3JlLnByb3RvLnYxLlBoeXNpY2FsU3RyZWFtVHlwZVIMcGh5c2ljYWxUeXBlEjUKFmdlbmVyYWxpemVk" +
            "X3N0YXRlbWVudHMYAyABKAhSFWdlbmVyYWxpemVkU3RhdGVtZW50cxIZCghyZGZfc3RhchgEIAEoCFIH" +
            "cmRmU3RhchItChNtYXhfbmFtZV90YWJsZV9zaXplGAkgASgNUhBtYXhOYW1lVGFibGVTaXplEjEKFW1h" +
            "eF9wcmVmaXhfdGFibGVfc2l6ZRgKIAEoDVISbWF4UHJlZml4VGFibGVTaXplEjUKF21heF9kYXRhdHlw" +
            "ZV90YWJsZV9zaXplGAsgASgNUhRtYXhEYXRhdHlwZVRhYmxlU2l6ZRJXCgxsb2dpY2FsX3R5cGUYDiAB" +
            "KA4yNC5ldS5vc3RyenljaWVsLmplbGx5LmNvcmUucHJvdG8udjEuTG9naWNhbFN0cmVhbVR5cGVSC2xv" +
            "Z2ljYWxUeXBlEhgKB3ZlcnNpb24YDyABKA1SB3ZlcnNpb24i1wUKDFJkZlN0cmVhbVJvdxJPCgdvcHRp" +
            "b25zGAEgASgLMjMuZXUub3N0cnp5Y2llbC5qZWxseS5jb3JlLnByb3RvLnYxLlJkZlN0cmVhbU9wdGlv" +
            "bnNIAFIHb3B0aW9ucxJGCgZ0cmlwbGUYAiABKAsyLC5ldS5vc3RyenljaWVsLmplbGx5LmNvcmUucHJv" +
            "dG8udjEuUmRmVHJpcGxlSABSBnRyaXBsZRJACgRxdWFkGAMgASgLMiouZXUub3N0cnp5Y2llbC5qZWxs" +
            "eS5jb3JlLnByb3RvLnYxLlJkZlF1YWRIAFIEcXVhZBJTCgtncmFwaF9zdGFydBgEIAEoCzIwLmV1Lm9z" +
            "dHJ6eWNpZWwuamVsbHkuY29yZS5wcm90by52MS5SZGZHcmFwaFN0YXJ0SABSCmdyYXBoU3RhcnQSTQoJ" +
            "Z3JhcGhfZW5kGAUgASgLMi4uZXUub3N0cnp5Y2llbC5qZWxseS5jb3JlLnByb3RvLnYxLlJkZkdyYXBo" +
            "RW5kSABSCGdyYXBoRW5kEloKCW5hbWVzcGFjZRgGIAEoCzI6LmV1Lm9zdHJ6eWNpZWwuamVsbHkuY29y" +
            "ZS5wcm90by52MS5SZGZOYW1lc3BhY2VEZWNsYXJhdGlvbkgAUgluYW1lc3BhY2USRQoEbmFtZRgJIAEo" +
            "CzIvLmV1Lm9zdHJ6eWNpZWwuamVsbHkuY29yZS5wcm90by52MS5SZGZOYW1lRW50cnlIAFIEbmFtZRJL" +
            "CgZwcmVmaXgYCiABKAsyMS5ldS5vc3RyenljaWVsLmplbGx5LmNvcmUucHJvdG8udjEuUmRmUHJlZml4" +
            "RW50cnlIAFIGcHJlZml4ElEKCGRhdGF0eXBlGAsgASgLMjMuZXUub3N0cnp5Y2llbC5qZWxseS5jb3Jl" +
            "LnByb3RvLnYxLlJkZkRhdGF0eXBlRW50cnlIAFIIZGF0YXR5cGVCBQoDcm93Iu8BCg5SZGZTdHJlYW1G" +
            "cmFtZRJDCgRyb3dzGAEgAygLMi8uZXUub3N0cnp5Y2llbC5qZWxseS5jb3JlLnByb3RvLnYxLlJkZlN0" +
            "cmVhbVJvd1IEcm93cxJbCghtZXRhZGF0YRgPIAMoCzI/LmV1Lm9zdHJ6eWNpZWwuamVsbHkuY29yZS5w" +
            "cm90by52MS5SZGZTdHJlYW1GcmFtZS5NZXRhZGF0YUVudHJ5UghtZXRhZGF0YRo7Cg1NZXRhZGF0YUVu" +
            "dHJ5EhAKA2tleRgBIAEoCVIDa2V5EhQKBXZhbHVlGAIgASgMUgV2YWx1ZToCOAEqnQEKElBoeXNpY2Fs" +
            "U3RyZWFtVHlwZRIkCiBQSFlTSUNBTF9TVFJFQU1fVFlQRV9VTlNQRUNJRklFRBAAEiAKHFBIWVNJQ0FM" +
            "X1NUUkVBTV9UWVBFX1RSSVBMRVMQARIeChpQSFlTSUNBTF9TVFJFQU1fVFlQRV9RVUFEUxACEh8KG1BI" +
            "WVNJQ0FMX1NUUkVBTV9UWVBFX0dSQVBIUxADKsQCChFMb2dpY2FsU3RyZWFtVHlwZRIjCh9MT0dJQ0FM" +
            "X1NUUkVBTV9UWVBFX1VOU1BFQ0lGSUVEEAASJAogTE9HSUNBTF9TVFJFQU1fVFlQRV9GTEFUX1RSSVBM" +
            "RVMQARIiCh5MT0dJQ0FMX1NUUkVBTV9UWVBFX0ZMQVRfUVVBRFMQAhIeChpMT0dJQ0FMX1NUUkVBTV9U" +
            "WVBFX0dSQVBIUxADEiAKHExPR0lDQUxfU1RSRUFNX1RZUEVfREFUQVNFVFMQBBImCiJMT0dJQ0FMX1NU" +
            "UkVBTV9UWVBFX1NVQkpFQ1RfR1JBUEhTEA0SJAogTE9HSUNBTF9TVFJFQU1fVFlQRV9OQU1FRF9HUkFQ" +
            "SFMQDhIwCixMT0dJQ0FMX1NUUkVBTV9UWVBFX1RJTUVTVEFNUEVEX05BTUVEX0dSQVBIUxByQgRIAVAB" +
            "SvFtCgcSBQAAggMBCggKAQwSAwAAEgoICgECEgMBACoKCAoBCBIDCAAcCqkBCgIICRIDCAAcMp0BIEpl" +
            "bGx5IFJERiBzZXJpYWxpemF0aW9uIHdpdGggUHJvdG9jb2wgQnVmZmVycy4KIFNwZWNpZmljYXRpb24g" +
            "ZG9jdW1lbnQ6IAogaHR0cHM6Ly93M2lkLm9yZy9qZWxseS8xLjEuMS9zcGVjaWZpY2F0aW9uL3Nlcmlh" +
            "bGl6YXRpb24KIFByb3RvY29sIHZlcnNpb246IDEuMS4xCgoICgEIEgMJACIKCQoCCAoSAwkAIgpsCgIE" +
            "ABIEDgAjARpgIFJERiBJUklzCiBUaGUgSVJJcyBhcmUgcmVjb25zdHJ1Y3RlZCBieSB0aGUgY29uc3Vt" +
            "ZXIgdXNpbmcgdGhlIHByZWZpeCBhbmQgbmFtZQogbG9va3VwIHRhYmxlcy4KCgoKAwQAARIDDggOCoYE" +
            "CgQEAAIAEgMZAhca+AMgMS1iYXNlZCwgcmVmZXJzIHRvIGFuIGVudHJ5IGluIHRoZSBwcmVmaXggbG9v" +
            "a3VwLgoKIDAgc2lnbmlmaWVzICJ1c2UgdGhlIHNhbWUgcHJlZml4X2lkIGFzIGluIHRoZSBwcmV2aW91" +
            "cyBJUkkiLgogRm9yIHRoaXMgdG8gd29yaywgSVJJcyBtdXN0IGJlIHByb2Nlc3NlZCBzdHJpY3RseSBp" +
            "biBvcmRlcjogZmlyc3RseSBieQogc3RyZWFtIHJvdywgdGhlbiBieSB0ZXJtIChzdWJqZWN0LCBwcmVk" +
            "aWNhdGUsIG9iamVjdCwgZ3JhcGgpLiBUaGlzIGFsc28KIGFwcGxpZXMgcmVjdXJzaXZlbHkgdG8gUkRG" +
            "LXN0YXIgcXVvdGVkIHRyaXBsZXMuCgogSWYgMCBhcHBlYXJzIGluIHRoZSBmaXJzdCBJUkkgb2YgdGhl" +
            "IHN0cmVhbSAoYW5kIGluIGFueSBzdWJzZXF1ZW50IElSSSksCiB0aGlzIHNob3VsZCBiZSBpbnRlcnBy" +
            "ZXRlZCBhcyBhbiBlbXB0eSAoIiIpIHByZWZpeC4gVGhpcyBpcyBmb3IgZXhhbXBsZQogdXNlZCB3aGVu" +
            "IHRoZSBwcmVmaXggbG9va3VwIHRhYmxlIGlzIGRpc2FibGVkLgoKDAoFBAACAAUSAxkCCAoMCgUEAAIA" +
            "ARIDGQkSCgwKBQQAAgADEgMZFRYK/AEKBAQAAgESAyICFRruASAxLWJhc2VkLCByZWZlcnMgdG8gYW4g" +
            "ZW50cnkgaW4gdGhlIG5hbWUgbG9va3VwLgoKIDAgc2lnbmlmaWVzICJ1c2UgdGhlIHByZXZpb3VzIG5h" +
            "bWVfaWQgKyAxIi4gVGhpcyByZXF1aXJlcyB0aGUgc2FtZSBvcmRlcgogZ3VhcmFudGVlcyBhcyBwcmVm" +
            "aXhlcy4KCiBJZiAwIGFwcGVhcnMgaW4gdGhlIGZpcnN0IElSSSBvZiB0aGUgc3RyZWFtLCBpdCBzaG91" +
            "bGQgYmUgaW50ZXJwcmV0ZWQgYXMKIG5hbWVfaWQgPSAxLgoKDAoFBAACAQUSAyICCAoMCgUEAAIBARID" +
            "IgkQCgwKBQQAAgEDEgMiExQKGgoCBAESBCYANAEaDiBSREYgbGl0ZXJhbHMKCgoKAwQBARIDJggSCjoK" +
            "BAQBAgASAygCERotIFRoZSBsZXhpY2FsIGZvcm0gb2YgdGhlIGxpdGVyYWwgKHJlcXVpcmVkKS4KCgwK" +
            "BQQBAgAFEgMoAggKDAoFBAECAAESAygJDAoMCgUEAQIAAxIDKA8QCnQKBAQBCAASBCwCMwMaZiBMaXRl" +
            "cmFsIGtpbmQg4oCTIGF0IG1vc3Qgb25lIG9mIHRoZXNlIGZpZWxkIG1heSBiZSBzZXQuCiBJZiBub25l" +
            "IGlzIHNldCwgdGhlbiBpdCdzIGEgc2ltcGxlIGxpdGVyYWwuCgoMCgUEAQgAARIDLAgTCiYKBAQBAgES" +
            "Ay4EFxoZIExhbmd1YWdlLXRhZ2dlZCBzdHJpbmcuCgoMCgUEAQIBBRIDLgQKCgwKBQQBAgEBEgMuCxIK" +
            "DAoFBAECAQMSAy4VFgrGAQoEBAECAhIDMgQYGrgBIFR5cGVkIGxpdGVyYWwuIFRoZSBkYXRhdHlwZSBp" +
            "cyBhIHJlZmVyZW5jZSB0byBhbiBlbnRyeSBpbiB0aGUKIGRhdGF0eXBlIGxvb2t1cC4gVGhpcyB2YWx1" +
            "ZSBpcyAxLWJhc2VkIGFuZCB0aGUgdmFsdWUgb2YgMAogaXMgaW52YWxpZCAoaW4gY29udHJhc3QgdG8g" +
            "cHJlZml4X2lkIGFuZCBuYW1lX2lkIGluIFJkZklyaSkuCgoMCgUEAQICBRIDMgQKCgwKBQQBAgIBEgMy" +
            "CxMKDAoFBAECAgMSAzIWFwo9CgIEAhIENwA4ARoxIEVtcHR5IG1lc3NhZ2UgaW5kaWNhdGluZyB0aGUg" +
            "ZGVmYXVsdCBSREYgZ3JhcGguCgoKCgMEAgESAzcIFwqgBQoCBAMSBEgAbwEakwUgUkRGIHRyaXBsZQoK" +
            "IEZvciBlYWNoIHRlcm0gKHN1YmplY3QsIHByZWRpY2F0ZSwgb2JqZWN0KSwgdGhlIGZpZWxkcyBhcmUg" +
            "cmVwZWF0ZWQgZm9yCiBwZXJmb3JtYW5jZSByZWFzb25zLiBUaGlzIGlzIHRvIGF2b2lkIHRoZSBuZWVk" +
            "IGZvciBib3hpbmcgZWFjaCB0ZXJtIGluIGEKIHNlcGFyYXRlIG1lc3NhZ2UuCgogTm90ZTogdGhpcyBt" +
            "ZXNzYWdlIGFsbG93cyBmb3IgcmVwcmVzZW50aW5nIGdlbmVyYWxpemVkIFJERiB0cmlwbGVzIChmb3IK" +
            "IGV4YW1wbGUsIHdpdGggbGl0ZXJhbHMgYXMgcHJlZGljYXRlcykuIFdoZXRoZXIgdGhpcyBpcyB1c2Vk" +
            "IGluIHRoZSBzdHJlYW0KIGlzIGRldGVybWluZWQgYnkgdGhlIHN0cmVhbSBvcHRpb25zIChzZWUgUmRm" +
            "U3RyZWFtT3B0aW9ucykuCgogSWYgbm8gZmllbGQgaW4gYSBnaXZlbiBvbmVvZiBpcyBzZXQsIHRoZSB0" +
            "ZXJtIGlzIGludGVycHJldGVkIGFzIGEgcmVwZWF0ZWQKIHRlcm0g4oCTIHRoZSBzYW1lIGFzIHRoZSB0" +
            "ZXJtIGluIHRoZSBzYW1lIHBvc2l0aW9uIGluIHRoZSBwcmV2aW91cyB0cmlwbGUuCiBJbiB0aGUgZmly" +
            "c3QgdHJpcGxlIG9mIHRoZSBzdHJlYW0sIGFsbCB0ZXJtcyBtdXN0IGJlIHNldC4KIEFsbCB0ZXJtcyBt" +
            "dXN0IGFsc28gYmUgc2V0IGluIHF1b3RlZCB0cmlwbGVzIChSREYtc3RhcikuCgoKCgMEAwESA0gIEQoe" +
            "CgQEAwgAEgRKAlQDGhAgVHJpcGxlIHN1YmplY3QKCgwKBQQDCAABEgNKCA8KEgoEBAMCABIDTAQcGgUg" +
            "SVJJCgoMCgUEAwIABhIDTAQKCgwKBQQDAgABEgNMEhcKDAoFBAMCAAMSA0waGwoZCgQEAwIBEgNOBB4a" +
            "DCBCbGFuayBub2RlCgoMCgUEAwIBBRIDTgQKCgwKBQQDAgEBEgNOEhkKDAoFBAMCAQMSA04cHQo/CgQE" +
            "AwICEgNRBCAaMiBMaXRlcmFsCiBPbmx5IHZhbGlkIGluIGEgZ2VuZXJhbGl6ZWQgUkRGIHN0cmVhbS4K" +
            "CgwKBQQDAgIGEgNRBA4KDAoFBAMCAgESA1ESGwoMCgUEAwICAxIDUR4fCiUKBAQDAgMSA1MEJBoYIFJE" +
            "Ri1zdGFyIHF1b3RlZCB0cmlwbGUKCgwKBQQDAgMGEgNTBA0KDAoFBAMCAwESA1MSHwoMCgUEAwIDAxID" +
            "UyIjCiAKBAQDCAESBFcCYgMaEiBUcmlwbGUgcHJlZGljYXRlCgoMCgUEAwgBARIDVwgRChIKBAQDAgQS" +
            "A1kEHBoFIElSSQoKDAoFBAMCBAYSA1kECgoMCgUEAwIEARIDWRIXCgwKBQQDAgQDEgNZGhsKQgoEBAMC" +
            "BRIDXAQeGjUgQmxhbmsgbm9kZQogT25seSB2YWxpZCBpbiBhIGdlbmVyYWxpemVkIFJERiBzdHJlYW0u" +
            "CgoMCgUEAwIFBRIDXAQKCgwKBQQDAgUBEgNcEhkKDAoFBAMCBQMSA1wcHQo/CgQEAwIGEgNfBCAaMiBM" +
            "aXRlcmFsCiBPbmx5IHZhbGlkIGluIGEgZ2VuZXJhbGl6ZWQgUkRGIHN0cmVhbS4KCgwKBQQDAgYGEgNf" +
            "BA4KDAoFBAMCBgESA18SGwoMCgUEAwIGAxIDXx4fCiUKBAQDAgcSA2EEJBoYIFJERi1zdGFyIHF1b3Rl" +
            "ZCB0cmlwbGUKCgwKBQQDAgcGEgNhBA0KDAoFBAMCBwESA2ESHwoMCgUEAwIHAxIDYSIjCh0KBAQDCAIS" +
            "BGUCbgMaDyBUcmlwbGUgb2JqZWN0CgoMCgUEAwgCARIDZQgOChIKBAQDAggSA2cEHBoFIElSSQoKDAoF" +
            "BAMCCAYSA2cECgoMCgUEAwIIARIDZxIXCgwKBQQDAggDEgNnGhsKGQoEBAMCCRIDaQQfGgwgQmxhbmsg" +
            "bm9kZQoKDAoFBAMCCQUSA2kECgoMCgUEAwIJARIDaRIZCgwKBQQDAgkDEgNpHB4KFgoEBAMCChIDawQh" +
            "GgkgTGl0ZXJhbAoKDAoFBAMCCgYSA2sEDgoMCgUEAwIKARIDaxIbCgwKBQQDAgoDEgNrHiAKJQoEBAMC" +
            "CxIDbQQlGhggUkRGLXN0YXIgcXVvdGVkIHRyaXBsZQoKDAoFBAMCCwYSA20EDQoMCgUEAwILARIDbRIf" +
            "CgwKBQQDAgsDEgNtIiQKjwQKAgQEEgV8AK8BARqBBCBSREYgcXVhZAoKIEZpZWxkcyAx4oCTMTIgYXJl" +
            "IHJlcGVhdGVkIGZyb20gUmRmVHJpcGxlIGZvciBwZXJmb3JtYW5jZSByZWFzb25zLgoKIFNpbWlsYXJs" +
            "eSB0byBSZGZUcmlwbGUsIHRoaXMgbWVzc2FnZSBhbGxvd3MgZm9yIHJlcHJlc2VudGluZyBnZW5lcmFs" +
            "aXplZAogUkRGIHF1YWRzIChmb3IgZXhhbXBsZSwgd2l0aCBsaXRlcmFscyBhcyBwcmVkaWNhdGVzKS4g" +
            "V2hldGhlciB0aGlzIGlzIHVzZWQKIGluIHRoZSBzdHJlYW0gaXMgZGV0ZXJtaW5lZCBieSB0aGUgc3Ry" +
            "ZWFtIG9wdGlvbnMgKHNlZSBSZGZTdHJlYW1PcHRpb25zKS4KCiBJZiBubyBmaWVsZCBpbiBhIGdpdmVu" +
            "IG9uZW9mIGlzIHNldCwgdGhlIHRlcm0gaXMgaW50ZXJwcmV0ZWQgYXMgYSByZXBlYXRlZAogdGVybSDi" +
            "gJMgdGhlIHNhbWUgYXMgdGhlIHRlcm0gaW4gdGhlIHNhbWUgcG9zaXRpb24gaW4gdGhlIHByZXZpb3Vz" +
            "IHF1YWQuCiBJbiB0aGUgZmlyc3QgcXVhZCBvZiB0aGUgc3RyZWFtLCBhbGwgdGVybXMgbXVzdCBiZSBz" +
            "ZXQuCgoKCgMEBAESA3wIDwodCgQEBAgAEgV+AogBAxoOIFF1YWQgc3ViamVjdAoKDAoFBAQIAAESA34I" +
            "DwoTCgQEBAIAEgSAAQQcGgUgSVJJCgoNCgUEBAIABhIEgAEECgoNCgUEBAIAARIEgAESFwoNCgUEBAIA" +
            "AxIEgAEaGwoaCgQEBAIBEgSCAQQeGgwgQmxhbmsgbm9kZQoKDQoFBAQCAQUSBIIBBAoKDQoFBAQCAQES" +
            "BIIBEhkKDQoFBAQCAQMSBIIBHB0KQAoEBAQCAhIEhQEEIBoyIExpdGVyYWwKIE9ubHkgdmFsaWQgaW4g" +
            "YSBnZW5lcmFsaXplZCBSREYgc3RyZWFtLgoKDQoFBAQCAgYSBIUBBA4KDQoFBAQCAgESBIUBEhsKDQoF" +
            "BAQCAgMSBIUBHh8KJgoEBAQCAxIEhwEEJBoYIFJERi1zdGFyIHF1b3RlZCB0cmlwbGUKCg0KBQQEAgMG" +
            "EgSHAQQNCg0KBQQEAgMBEgSHARIfCg0KBQQEAgMDEgSHASIjCiAKBAQECAESBosBApYBAxoQIFF1YWQg" +
            "cHJlZGljYXRlCgoNCgUEBAgBARIEiwEIEQoTCgQEBAIEEgSNAQQcGgUgSVJJCgoNCgUEBAIEBhIEjQEE" +
            "CgoNCgUEBAIEARIEjQESFwoNCgUEBAIEAxIEjQEaGwpDCgQEBAIFEgSQAQQeGjUgQmxhbmsgbm9kZQog" +
            "T25seSB2YWxpZCBpbiBhIGdlbmVyYWxpemVkIFJERiBzdHJlYW0uCgoNCgUEBAIFBRIEkAEECgoNCgUE" +
            "BAIFARIEkAESGQoNCgUEBAIFAxIEkAEcHQpACgQEBAIGEgSTAQQgGjIgTGl0ZXJhbAogT25seSB2YWxp" +
            "ZCBpbiBhIGdlbmVyYWxpemVkIFJERiBzdHJlYW0uCgoNCgUEBAIGBhIEkwEEDgoNCgUEBAIGARIEkwES" +
            "GwoNCgUEBAIGAxIEkwEeHwomCgQEBAIHEgSVAQQkGhggUkRGLXN0YXIgcXVvdGVkIHRyaXBsZQoKDQoF" +
            "BAQCBwYSBJUBBA0KDQoFBAQCBwESBJUBEh8KDQoFBAQCBwMSBJUBIiMKHQoEBAQIAhIGmQECogEDGg0g" +
            "UXVhZCBvYmplY3QKCg0KBQQECAIBEgSZAQgOChMKBAQEAggSBJsBBBwaBSBJUkkKCg0KBQQEAggGEgSb" +
            "AQQKCg0KBQQEAggBEgSbARIXCg0KBQQEAggDEgSbARobChoKBAQEAgkSBJ0BBB8aDCBCbGFuayBub2Rl" +
            "CgoNCgUEBAIJBRIEnQEECgoNCgUEBAIJARIEnQESGQoNCgUEBAIJAxIEnQEcHgoXCgQEBAIKEgSfAQQh" +
            "GgkgTGl0ZXJhbAoKDQoFBAQCCgYSBJ8BBA4KDQoFBAQCCgESBJ8BEhsKDQoFBAQCCgMSBJ8BHiAKJgoE" +
            "BAQCCxIEoQEEJRoYIFJERi1zdGFyIHF1b3RlZCB0cmlwbGUKCg0KBQQEAgsGEgShAQQNCg0KBQQEAgsB" +
            "EgShARIfCg0KBQQEAgsDEgShASIkChwKBAQECAMSBqUBAq4BAxoMIFF1YWQgZ3JhcGgKCg0KBQQECAMB" +
            "EgSlAQgNChMKBAQEAgwSBKcBBCAaBSBJUkkKCg0KBQQEAgwGEgSnAQQKCg0KBQQEAgwBEgSnARUaCg0K" +
            "BQQEAgwDEgSnAR0fChoKBAQEAg0SBKkBBCIaDCBCbGFuayBub2RlCgoNCgUEBAINBRIEqQEECgoNCgUE" +
            "BAINARIEqQEVHAoNCgUEBAINAxIEqQEfIQodCgQEBAIOEgSrAQQqGg8gRGVmYXVsdCBncmFwaAoKDQoF" +
            "BAQCDgYSBKsBBBMKDQoFBAQCDgESBKsBFSQKDQoFBAQCDgMSBKsBJykKQgoEBAQCDxIErQEEJBo0IExp" +
            "dGVyYWwg4oCTIG9ubHkgdmFsaWQgZm9yIGdlbmVyYWxpemVkIFJERiBzdHJlYW1zCgoNCgUEBAIPBhIE" +
            "rQEEDgoNCgUEBAIPARIErQEVHgoNCgUEBAIPAxIErQEhIwqoAQoCBAUSBrUBAMABARqZASBTdGFydCBv" +
            "ZiBhIGdyYXBoIGluIGEgR1JBUEhTIHN0cmVhbQoKIEluIGNvbnRyYXN0IHRvIFJkZlF1YWQsIHNldHRp" +
            "bmcgdGhlIGdyYXBoIG9uZW9mIHRvIHNvbWUgdmFsdWUKIGlzIGFsd2F5cyByZXF1aXJlZC4gTm8gcmVw" +
            "ZWF0ZWQgdGVybXMgYXJlIGFsbG93ZWQuCgoLCgMEBQESBLUBCBUKDgoEBAUIABIGtgECvwEDCg0KBQQF" +
            "CAABEgS2AQgNChMKBAQFAgASBLgBBB8aBSBJUkkKCg0KBQQFAgAGEgS4AQQKCg0KBQQFAgABEgS4ARUa" +
            "Cg0KBQQFAgADEgS4AR0eChoKBAQFAgESBLoBBCEaDCBCbGFuayBub2RlCgoNCgUEBQIBBRIEugEECgoN" +
            "CgUEBQIBARIEugEVHAoNCgUEBQIBAxIEugEfIAodCgQEBQICEgS8AQQpGg8gRGVmYXVsdCBncmFwaAoK" +
            "DQoFBAUCAgYSBLwBBBMKDQoFBAUCAgESBLwBFSQKDQoFBAUCAgMSBLwBJygKQgoEBAUCAxIEvgEEIxo0" +
            "IExpdGVyYWwg4oCTIG9ubHkgdmFsaWQgZm9yIGdlbmVyYWxpemVkIFJERiBzdHJlYW1zCgoNCgUEBQID" +
            "BhIEvgEEDgoNCgUEBQIDARIEvgEVHgoNCgUEBQIDAxIEvgEhIgoxCgIEBhIGwwEAxAEBGiMgRW5kIG9m" +
            "IGEgZ3JhcGggaW4gYSBHUkFQSFMgc3RyZWFtCgoLCgMEBgESBMMBCBMKxAQKAgQHEgbRAQDXAQEatQQg" +
            "RXhwbGljaXQgbmFtZXNwYWNlIGRlY2xhcmF0aW9uCgogVGhpcyBkb2VzIG5vdCBjb3JyZXNwb25kIHRv" +
            "IGFueSBjb25zdHJ1Y3QgaW4gdGhlIFJERiBBYnN0cmFjdCBTeW50YXguCiBSYXRoZXIsIGl0IGlzIGEg" +
            "aGludCB0byB0aGUgY29uc3VtZXIgdGhhdCB0aGUgZ2l2ZW4gSVJJIHByZWZpeCAobmFtZXNwYWNlKQog" +
            "bWF5IGJlIGFzc29jaWF0ZWQgd2l0aCBhIHNob3J0ZXIgbmFtZSwgbGlrZSBpbiBUdXJ0bGUgc3ludGF4" +
            "OgogUFJFRklYIGV4OiA8aHR0cDovL2V4YW1wbGUub3JnLz4KCiBUaGVzZSBzaG9ydCBuYW1lcyAoaGVy" +
            "ZSAiZXg6IikgYXJlIE5PVCB1c2VkIGluIHRoZSBSREYgc3RhdGVtZW50IGVuY29kaW5nLgogVGhpcyBp" +
            "cyBhIHB1cmVseSBjb3NtZXRpYyBmZWF0dXJlIHVzZWZ1bCBpbiBjYXNlcyB3aGVyZSB5b3Ugd2FudCB0" +
            "bwogcHJlc2VydmUgdGhlIG5hbWVzcGFjZSBkZWNsYXJhdGlvbnMgZnJvbSB0aGUgb3JpZ2luYWwgUkRG" +
            "IGRvY3VtZW50LgogVGhlc2UgZGVjbGFyYXRpb25zIGhhdmUgbm90aGluZyBpbiBjb21tb24gd2l0aCB0" +
            "aGUgcHJlZml4IGxvb2t1cCB0YWJsZS4KCgsKAwQHARIE0QEIHwpTCgQEBwIAEgTUAQISGkUgU2hvcnQg" +
            "bmFtZSBvZiB0aGUgbmFtZXNwYWNlIChlLmcuLCAiZXgiKQogRG8gTk9UIGluY2x1ZGUgdGhlIGNvbG9u" +
            "LgoKDQoFBAcCAAUSBNQBAggKDQoFBAcCAAESBNQBCQ0KDQoFBAcCAAMSBNQBEBEKQgoEBAcCARIE1gEC" +
            "Exo0IElSSSBvZiB0aGUgbmFtZXNwYWNlIChlLmcuLCAiaHR0cDovL2V4YW1wbGUub3JnLyIpCgoNCgUE" +
            "BwIBBhIE1gECCAoNCgUEBwIBARIE1gEJDgoNCgUEBwIBAxIE1gEREgouCgIECBIG2gEA4gEBGiAgRW50" +
            "cnkgaW4gdGhlIG5hbWUgbG9va3VwIHRhYmxlCgoLCgMECAESBNoBCBQKtAEKBAQIAgASBN8BAhAapQEg" +
            "MS1iYXNlZCBpZGVudGlmaWVyCiBJZiBpZD0wLCBpdCBzaG91bGQgYmUgaW50ZXJwcmV0ZWQgYXMgcHJl" +
            "dmlvdXNfaWQgKyAxLgogSWYgaWQ9MCBhcHBlYXJzIGluIHRoZSBmaXJzdCBSZGZOYW1lRW50cnkgb2Yg" +
            "dGhlIHN0cmVhbSwgaXQgc2hvdWxkIGJlCiBpbnRlcnByZXRlZCBhcyAxLgoKDQoFBAgCAAUSBN8BAggK" +
            "DQoFBAgCAAESBN8BCQsKDQoFBAgCAAMSBN8BDg8KMQoEBAgCARIE4QECExojIFZhbHVlIG9mIHRoZSBu" +
            "YW1lIChVVEYtOCBlbmNvZGVkKQoKDQoFBAgCAQUSBOEBAggKDQoFBAgCAQESBOEBCQ4KDQoFBAgCAQMS" +
            "BOEBERIKpwIKAgQJEgbqAQDyAQEamAIgRW50cnkgaW4gdGhlIHByZWZpeCBsb29rdXAgdGFibGUKCiBO" +
            "b3RlOiB0aGUgcHJlZml4ZXMgaW4gdGhlIGxvb2t1cCB0YWJsZSBjYW4gYmUgYXJiaXRyYXJ5IHN0cmlu" +
            "Z3MsIGFuZCBhcmUKIE5PVCBtZWFudCB0byBiZSB1c2VyLWZhY2luZy4gVGhleSBhcmUgb25seSB1c2Vk" +
            "IGZvciBJUkkgY29tcHJlc3Npb24uCiBUbyB0cmFuc21pdCB1c2VyLWZhY2luZyBuYW1lc3BhY2UgZGVj" +
            "bGFyYXRpb25zIGZvciBjb3NtZXRpYyBwdXJwb3NlcywgdXNlCiBSZGZOYW1lc3BhY2VEZWNsYXJhdGlv" +
            "bi4KCgsKAwQJARIE6gEIFgq2AQoEBAkCABIE7wECEBqnASAxLWJhc2VkIGlkZW50aWZpZXIKIElmIGlk" +
            "PTAsIGl0IHNob3VsZCBiZSBpbnRlcnByZXRlZCBhcyBwcmV2aW91c19pZCArIDEuCiBJZiBpZD0wIGFw" +
            "cGVhcnMgaW4gdGhlIGZpcnN0IFJkZlByZWZpeEVudHJ5IG9mIHRoZSBzdHJlYW0sIGl0IHNob3VsZCBi" +
            "ZQogaW50ZXJwcmV0ZWQgYXMgMS4KCg0KBQQJAgAFEgTvAQIICg0KBQQJAgABEgTvAQkLCg0KBQQJAgAD" +
            "EgTvAQ4PCjMKBAQJAgESBPEBAhMaJSBWYWx1ZSBvZiB0aGUgcHJlZml4IChVVEYtOCBlbmNvZGVkKQoK" +
            "DQoFBAkCAQUSBPEBAggKDQoFBAkCAQESBPEBCQ4KDQoFBAkCAQMSBPEBERIKMgoCBAoSBvUBAP0BARok" +
            "IEVudHJ5IGluIHRoZSBkYXRhdHlwZSBsb29rdXAgdGFibGUKCgsKAwQKARIE9QEIGAq4AQoEBAoCABIE" +
            "+gECEBqpASAxLWJhc2VkIGlkZW50aWZpZXIKIElmIGlkPTAsIGl0IHNob3VsZCBiZSBpbnRlcnByZXRl" +
            "ZCBhcyBwcmV2aW91c19pZCArIDEuCiBJZiBpZD0wIGFwcGVhcnMgaW4gdGhlIGZpcnN0IFJkZkRhdGF0" +
            "eXBlRW50cnkgb2YgdGhlIHN0cmVhbSwgaXQgc2hvdWxkIGJlCiBpbnRlcnByZXRlZCBhcyAxLgoKDQoF" +
            "BAoCAAUSBPoBAggKDQoFBAoCAAESBPoBCQsKDQoFBAoCAAMSBPoBDg8KNQoEBAoCARIE/AECExonIFZh" +
            "bHVlIG9mIHRoZSBkYXRhdHlwZSAoVVRGLTggZW5jb2RlZCkKCg0KBQQKAgEFEgT8AQIICg0KBQQKAgEB" +
            "EgT8AQkOCg0KBQQKAgEDEgT8ARESCiIKAgQLEgaAAgCbAgEaFCBSREYgc3RyZWFtIG9wdGlvbnMKCgsK" +
            "AwQLARIEgAIIGAp3CgQECwIAEgSDAgIZGmkgTmFtZSBvZiB0aGUgc3RyZWFtIChjb21wbGV0ZWx5IG9w" +
            "dGlvbmFsKS4KIFRoaXMgbWF5IGJlIHVzZWQgZm9yLCBlLmcuLCB0b3BpYyBuYW1lcyBpbiBhIHB1Yi9z" +
            "dWIgc3lzdGVtLgoKDQoFBAsCAAUSBIMCAggKDQoFBAsCAAESBIMCCRQKDQoFBAsCAAMSBIMCFxgKLQoE" +
            "BAsCARIEhQICJxofIFR5cGUgb2YgdGhlIHN0cmVhbSAocmVxdWlyZWQpCgoNCgUECwIBBhIEhQICFAoN" +
            "CgUECwIBARIEhQIVIgoNCgUECwIBAxIEhQIlJgpWCgQECwICEgSHAgIiGkggV2hldGhlciB0aGUgc3Ry" +
            "ZWFtIG1heSBjb250YWluIGdlbmVyYWxpemVkIHRyaXBsZXMsIHF1YWRzLCBvciBkYXRhc2V0cwoKDQoF" +
            "BAsCAgUSBIcCAgYKDQoFBAsCAgESBIcCBx0KDQoFBAsCAgMSBIcCICEKQgoEBAsCAxIEiQICFBo0IFdo" +
            "ZXRoZXIgdGhlIHN0cmVhbSBtYXkgY29udGFpbiBSREYtc3RhciBzdGF0ZW1lbnRzCgoNCgUECwIDBRIE" +
            "iQICBgoNCgUECwIDARIEiQIHDwoNCgUECwIDAxIEiQISEwpPCgQECwIEEgSMAgIhGkEgTWF4aW11bSBz" +
            "aXplIG9mIHRoZSBuYW1lIGxvb2t1cCB0YWJsZQogKHJlcXVpcmVkLCBtdXN0IGJlID49IDgpCgoNCgUE" +
            "CwIEBRIEjAICCAoNCgUECwIEARIEjAIJHAoNCgUECwIEAxIEjAIfIApgCgQECwIFEgSPAgIkGlIgTWF4" +
            "aW11bSBzaXplIG9mIHRoZSBwcmVmaXggbG9va3VwIHRhYmxlCiAocmVxdWlyZWQgaWYgdGhlIHByZWZp" +
            "eCBsb29rdXAgaXMgdXNlZCkKCg0KBQQLAgUFEgSPAgIICg0KBQQLAgUBEgSPAgkeCg0KBQQLAgUDEgSP" +
            "AiEjCmQKBAQLAgYSBJICAiYaViBNYXhpbXVtIHNpemUgb2YgdGhlIGRhdGF0eXBlIGxvb2t1cCB0YWJs" +
            "ZSAKIChyZXF1aXJlZCBpZiBkYXRhdHlwZSBsaXRlcmFscyBhcmUgdXNlZCkKCg0KBQQLAgYFEgSSAgII" +
            "Cg0KBQQLAgYBEgSSAgkgCg0KBQQLAgYDEgSSAiMlCngKBAQLAgcSBJUCAiYaaiBMb2dpY2FsIChSREYt" +
            "U1RhWC1iYXNlZCkgc3RyZWFtIHR5cGUKIEluIGNvbnRyYXN0IHRvIHRoZSBwaHlzaWNhbCB0eXBlLCB0" +
            "aGlzIGZpZWxkIGlzIGVudGlyZWx5IG9wdGlvbmFsLgoKDQoFBAsCBwYSBJUCAhMKDQoFBAsCBwESBJUC" +
            "FCAKDQoFBAsCBwMSBJUCIyUKqwEKBAQLAggSBJoCAhYanAEgUHJvdG9jb2wgdmVyc2lvbiAocmVxdWly" +
            "ZWQpCiBGb3IgSmVsbHkgMS4wLnggdmFsdWUgbXVzdCBiZSAxLgogRm9yIEplbGx5IDEuMS54IHZhbHVl" +
            "IG11c3QgYmUgMi4KIEZvciBjdXN0b20gZXh0ZW5zaW9ucywgdGhlIHZhbHVlIG11c3QgYmUgMTAwMDAg" +
            "b3IgaGlnaGVyLgoKDQoFBAsCCAUSBJoCAggKDQoFBAsCCAESBJoCCRAKDQoFBAsCCAMSBJoCExUKqwEK" +
            "AgUAEgagAgCpAgEanAEgUGh5c2ljYWwgc3RyZWFtIHR5cGUKIFRoaXMgZGV0ZXJtaW5lcyBob3cgdGhl" +
            "IGRhdGEgaXMgZW5jb2RlZCBpbiB0aGUgc3RyZWFtLCBub3QgdGhlIGxvZ2ljYWwKIHN0cnVjdHVyZSBv" +
            "ZiB0aGUgZGF0YS4gU2VlIExvZ2ljYWxTdHJlYW1UeXBlIGZvciB0aGUgbGF0dGVyLgoKCwoDBQABEgSg" +
            "AgUXCjMKBAUAAgASBKICAicaJSBVbnNwZWNpZmllZCBzdHJlYW0gdHlwZSDigJMgaW52YWxpZAoKDQoF" +
            "BQACAAESBKICAiIKDQoFBQACAAISBKICJSYKGwoEBQACARIEpAICIxoNIFJERiB0cmlwbGVzCgoNCgUF" +
            "AAIBARIEpAICHgoNCgUFAAIBAhIEpAIhIgoZCgQFAAICEgSmAgIhGgsgUkRGIHF1YWRzCgoNCgUFAAIC" +
            "ARIEpgICHAoNCgUFAAICAhIEpgIfIAotCgQFAAIDEgSoAgIiGh8gUkRGIHRyaXBsZXMgZ3JvdXBlZCBp" +
            "biBncmFwaHMKCg0KBQUAAgMBEgSoAgIdCg0KBQUAAgMCEgSoAiAhCukGCgIFARIGvgIA2AIBGtoGIExv" +
            "Z2ljYWwgc3RyZWFtIHR5cGUsIGFjY29yZGluZyB0byB0aGUgUkRGIFN0cmVhbSBUYXhvbm9teSAoUkRG" +
            "LVNUYVgpLgogVHlwZSAwIGlzIHJlc2VydmVkIGZvciB0aGUgdW5zcGVjaWZpZWQgc3RyZWFtIHR5cGUu" +
            "CiBUaGUgcmVzdCBvZiB0aGUgdHlwZSBudW1iZXJzIGZvbGxvdyB0aGUgdGF4b25vbWljYWwgc3RydWN0" +
            "dXJlIG9mIFJERi1TVGFYLgogRm9yIGV4YW1wbGU6IDEgaXMgYSBzdWJ0eXBlIG9mIDAsIDEzIGFuZCAy" +
            "MyBhcmUgc3VidHlwZXMgb2YgMywgCiAxMTQgaXMgYSBzdWJ0eXBlIG9mIDE0LCBldGMuCiAKIFR5cGVz" +
            "IDHigJM0IGNvcnJlc3BvbmQgdG8gdGhlIGZvdXIgYmFzZSBjb25jcmV0ZSBzdHJlYW0gdHlwZXMuIFRo" +
            "ZWlyIAogc3VidHlwZXMgY2FuIGJlIGluIG1vc3QgY2FzZXMgc2ltcGx5IHByb2Nlc3NlZCBpbiB0aGUg" +
            "c2FtZSB3YXkgYXMgCiB0aGUgYmFzZSB0eXBlcy4KIFRoZXJlZm9yZSwgaW1wbGVtZW50YXRpb25zIGNh" +
            "biB0YWtlIHRoZSBtb2R1bG8gMTAgb2YgdGhlIHN0cmVhbSAKIHR5cGUgdG8gZGV0ZXJtaW5lIHRoZSBi" +
            "YXNlIHR5cGUgb2YgdGhlIHN0cmVhbSBhbmQgdXNlIHRoaXMgaW5mb3JtYXRpb24gCiB0byBzZWxlY3Qg" +
            "dGhlIGFwcHJvcHJpYXRlIHByb2Nlc3NpbmcgbG9naWMuCgogUkRGLVNUYVggdmVyc2lvbjogMS4xLjIK" +
            "IGh0dHBzOi8vdzNpZC5vcmcvc3RheC8xLjEuMgoKIF4gVGhlIGFib3ZlIFVSTCBpcyB1c2VkIHRvIGF1" +
            "dG9tYXRpY2FsbHkgZGV0ZXJtaW5lIHRoZSB2ZXJzaW9uIG9mIFJERi1TVGFYCiBpbiB0aGUgSmVsbHkg" +
            "cHJvdG9jb2wgc3BlY2lmaWNhdGlvbi4gUGxlYXNlIGtlZXAgaXQgdXAtdG8tZGF0ZSBhbmQgaW4gdGhl" +
            "CiBzYW1lIGZvcm1hdC4KCgsKAwUBARIEvgIFFgozCgQFAQIAEgTAAgImGiUgVW5zcGVjaWZpZWQgc3Ry" +
            "ZWFtIHR5cGUg4oCTIGludmFsaWQKCg0KBQUBAgABEgTAAgIhCg0KBQUBAgACEgTAAiQlClcKBAUBAgES" +
            "BMMCAicaSSBGbGF0IFJERiB0cmlwbGUgc3RyZWFtCiBodHRwczovL3czaWQub3JnL3N0YXgvb250b2xv" +
            "Z3kjZmxhdFRyaXBsZVN0cmVhbQoKDQoFBQECAQESBMMCAiIKDQoFBQECAQISBMMCJSYKUwoEBQECAhIE" +
            "xgICJRpFIEZsYXQgUkRGIHF1YWQgc3RyZWFtCiBodHRwczovL3czaWQub3JnL3N0YXgvb250b2xvZ3kj" +
            "ZmxhdFF1YWRTdHJlYW0KCg0KBQUBAgIBEgTGAgIgCg0KBQUBAgICEgTGAiMkCkwKBAUBAgMSBMkCAiEa" +
            "PiBSREYgZ3JhcGggc3RyZWFtCiBodHRwczovL3czaWQub3JnL3N0YXgvb250b2xvZ3kjZ3JhcGhTdHJl" +
            "YW0KCg0KBQUBAgMBEgTJAgIcCg0KBQUBAgMCEgTJAh8gClAKBAUBAgQSBMwCAiMaQiBSREYgZGF0YXNl" +
            "dCBzdHJlYW0KIGh0dHBzOi8vdzNpZC5vcmcvc3RheC9vbnRvbG9neSNkYXRhc2V0U3RyZWFtCgoNCgUF" +
            "AQIEARIEzAICHgoNCgUFAQIEAhIEzAIhIgp5CgQFAQIFEgTQAgIqGmsgUkRGIHN1YmplY3QgZ3JhcGgg" +
            "c3RyZWFtIChzdWJ0eXBlIG9mIFJERiBncmFwaCBzdHJlYW0pCiBodHRwczovL3czaWQub3JnL3N0YXgv" +
            "b250b2xvZ3kjc3ViamVjdEdyYXBoU3RyZWFtCgoNCgUFAQIFARIE0AICJAoNCgUFAQIFAhIE0AInKQp3" +
            "CgQFAQIGEgTUAgIoGmkgUkRGIG5hbWVkIGdyYXBoIHN0cmVhbSAoc3VidHlwZSBvZiBSREYgZGF0YXNl" +
            "dCBzdHJlYW0pCiBodHRwczovL3czaWQub3JnL3N0YXgvb250b2xvZ3kjbmFtZWRHcmFwaFN0cmVhbQoK" +
            "DQoFBQECBgESBNQCAiIKDQoFBQECBgISBNQCJScKjwEKBAUBAgcSBNcCAjUagAEgUkRGIHRpbWVzdGFt" +
            "cGVkIG5hbWVkIGdyYXBoIHN0cmVhbSAoc3VidHlwZSBvZiBSREYgZGF0YXNldCBzdHJlYW0pCiBodHRw" +
            "czovL3czaWQub3JnL3N0YXgvb250b2xvZ3kjdGltZXN0YW1wZWROYW1lZEdyYXBoU3RyZWFtCgoNCgUF" +
            "AQIHARIE1wICLgoNCgUFAQIHAhIE1wIxNAoeCgIEDBIG2wIA9gIBGhAgUkRGIHN0cmVhbSByb3cKCgsK" +
            "AwQMARIE2wIIFAo6CgQEDAgAEgbdAgL1AgMaKiBFeGFjdGx5IG9uZSBvZiB0aGVzZSBmaWVsZHMgbXVz" +
            "dCBiZSBzZXQuCgoNCgUEDAgAARIE3QIICwpGCgQEDAIAEgTfAgQhGjggU3RyZWFtIG9wdGlvbnMuIE11" +
            "c3Qgb2NjdXIgYXQgdGhlIHN0YXJ0IG9mIHRoZSBzdHJlYW0uCgoNCgUEDAIABhIE3wIEFAoNCgUEDAIA" +
            "ARIE3wIVHAoNCgUEDAIAAxIE3wIfIApbCgQEDAIBEgTiAgQZGk0gUkRGIHRyaXBsZSBzdGF0ZW1lbnQu" +
            "CiBWYWxpZCBpbiBzdHJlYW1zIG9mIHBoeXNpY2FsIHR5cGUgVFJJUExFUyBvciBHUkFQSFMuCgoNCgUE" +
            "DAIBBhIE4gIEDQoNCgUEDAIBARIE4gIOFAoNCgUEDAIBAxIE4gIXGApSCgQEDAICEgTlAgQVGkQgUkRG" +
            "IHF1YWQgc3RhdGVtZW50LgogT25seSB2YWxpZCBpbiBzdHJlYW1zIG9mIHBoeXNpY2FsIHR5cGUgUVVB" +
            "RFMuCgoNCgUEDAICBhIE5QIECwoNCgUEDAICARIE5QIMEAoNCgUEDAICAxIE5QITFAqJAQoEBAwCAxIE" +
            "6AIEIhp7IEdyYXBoIGJvdW5kYXJ5OiBlbmRzIHRoZSBjdXJyZW50bHkgdHJhbnNtaXR0ZWQgZ3JhcGgg" +
            "YW5kIHN0YXJ0cyBhIG5ldyBvbmUKIE9ubHkgdmFsaWQgaW4gc3RyZWFtcyBvZiBwaHlzaWNhbCB0eXBl" +
            "IEdSQVBIUy4KCg0KBQQMAgMGEgToAgQRCg0KBQQMAgMBEgToAhIdCg0KBQQMAgMDEgToAiAhCpcBCgQE" +
            "DAIEEgTsAgQeGogBIEV4cGxpY2l0IGVuZCBvZiBhIGdyYXBoLgogU2lnbmFscyB0aGUgY29uc3VtZXIg" +
            "dGhhdCB0aGUgdHJhbnNtaXR0ZWQgZ3JhcGggaXMgY29tcGxldGUuCiBPbmx5IHZhbGlkIGluIHN0cmVh" +
            "bXMgb2YgcGh5c2ljYWwgdHlwZSBHUkFQSFMuCgoNCgUEDAIEBhIE7AIEDwoNCgUEDAIEARIE7AIQGQoN" +
            "CgUEDAIEAxIE7AIcHQovCgQEDAIFEgTuAgQqGiEgRXhwbGljaXQgbmFtZXNwYWNlIGRlY2xhcmF0aW9u" +
            "LgoKDQoFBAwCBQYSBO4CBBsKDQoFBAwCBQESBO4CHCUKDQoFBAwCBQMSBO4CKCkKLwoEBAwCBhIE8AIE" +
            "GhohIEVudHJ5IGluIHRoZSBuYW1lIGxvb2t1cCB0YWJsZS4KCg0KBQQMAgYGEgTwAgQQCg0KBQQMAgYB" +
            "EgTwAhEVCg0KBQQMAgYDEgTwAhgZCjEKBAQMAgcSBPICBB8aIyBFbnRyeSBpbiB0aGUgcHJlZml4IGxv" +
            "b2t1cCB0YWJsZS4KCg0KBQQMAgcGEgTyAgQSCg0KBQQMAgcBEgTyAhMZCg0KBQQMAgcDEgTyAhweCjMK" +
            "BAQMAggSBPQCBCMaJSBFbnRyeSBpbiB0aGUgZGF0YXR5cGUgbG9va3VwIHRhYmxlLgoKDQoFBAwCCAYS" +
            "BPQCBBQKDQoFBAwCCAESBPQCFR0KDQoFBAwCCAMSBPQCICIKQgoCBA0SBvkCAIIDARo0IFJERiBzdHJl" +
            "YW0gZnJhbWUg4oCTIGJhc2UgbWVzc2FnZSBmb3IgUkRGIHN0cmVhbXMuCgoLCgMEDQESBPkCCBYKGwoE" +
            "BA0CABIE+wICIRoNIFN0cmVhbSByb3dzCgoNCgUEDQIABBIE+wICCgoNCgUEDQIABhIE+wILFwoNCgUE" +
            "DQIAARIE+wIYHAoNCgUEDQIAAxIE+wIfIAr/AQoEBA0CARIEgQMCIxrwASBBcmJpdHJhcnkgbWV0YWRh" +
            "dGEKIFRoZSBrZXlzIGFyZSBVVEYtOCBlbmNvZGVkIHN0cmluZ3MsIHRoZSB2YWx1ZXMgYXJlIGJ5dGUg" +
            "YXJyYXlzLgogVGhpcyBtYXkgYmUgdXNlZCBieSBpbXBsZW1lbnRhdGlvbnMgaW4gYW55IHdheSB0aGV5" +
            "IHNlZSBmaXQuCiBUaGUgbWV0YWRhdGEgZG9lcyBub3QgYWZmZWN0IHRoZSBSREYgZGF0YSBpbiBhbnkg" +
            "d2F5LCB0cmVhdCBpdAogYXMgY29tbWVudHMgaW4gYSB0ZXh0IGZpbGUuCgoNCgUEDQIBBhIEgQMCFAoN" +
            "CgUEDQIBARIEgQMVHQoNCgUEDQIBAxIEgQMgImIGcHJvdG8z"
        );

    static final Descriptors.FileDescriptor descriptor;

    static final Descriptors.Descriptor eu_ostrzyciel_jelly_core_proto_v1_RdfIri_descriptor;

    static final Descriptors.Descriptor eu_ostrzyciel_jelly_core_proto_v1_RdfLiteral_descriptor;

    static final Descriptors.Descriptor eu_ostrzyciel_jelly_core_proto_v1_RdfDefaultGraph_descriptor;

    static final Descriptors.Descriptor eu_ostrzyciel_jelly_core_proto_v1_RdfTriple_descriptor;

    static final Descriptors.Descriptor eu_ostrzyciel_jelly_core_proto_v1_RdfQuad_descriptor;

    static final Descriptors.Descriptor eu_ostrzyciel_jelly_core_proto_v1_RdfGraphStart_descriptor;

    static final Descriptors.Descriptor eu_ostrzyciel_jelly_core_proto_v1_RdfGraphEnd_descriptor;

    static final Descriptors.Descriptor eu_ostrzyciel_jelly_core_proto_v1_RdfNamespaceDeclaration_descriptor;

    static final Descriptors.Descriptor eu_ostrzyciel_jelly_core_proto_v1_RdfNameEntry_descriptor;

    static final Descriptors.Descriptor eu_ostrzyciel_jelly_core_proto_v1_RdfPrefixEntry_descriptor;

    static final Descriptors.Descriptor eu_ostrzyciel_jelly_core_proto_v1_RdfDatatypeEntry_descriptor;

    static final Descriptors.Descriptor eu_ostrzyciel_jelly_core_proto_v1_RdfStreamOptions_descriptor;

    static final Descriptors.Descriptor eu_ostrzyciel_jelly_core_proto_v1_RdfStreamRow_descriptor;

    static final Descriptors.Descriptor eu_ostrzyciel_jelly_core_proto_v1_RdfStreamFrame_descriptor;

    static final Descriptors.Descriptor eu_ostrzyciel_jelly_core_proto_v1_RdfStreamFrame_MetadataEntry_descriptor;

    static {
        try {
            descriptor = Descriptors.FileDescriptor.buildFrom(
                DescriptorProtos.FileDescriptorProto.parseFrom(descriptorData),
                new Descriptors.FileDescriptor[] {}
            );
            eu_ostrzyciel_jelly_core_proto_v1_RdfIri_descriptor = descriptor.getMessageTypes().get(0);
            eu_ostrzyciel_jelly_core_proto_v1_RdfLiteral_descriptor = descriptor.getMessageTypes().get(1);
            eu_ostrzyciel_jelly_core_proto_v1_RdfDefaultGraph_descriptor = descriptor.getMessageTypes().get(2);
            eu_ostrzyciel_jelly_core_proto_v1_RdfTriple_descriptor = descriptor.getMessageTypes().get(3);
            eu_ostrzyciel_jelly_core_proto_v1_RdfQuad_descriptor = descriptor.getMessageTypes().get(4);
            eu_ostrzyciel_jelly_core_proto_v1_RdfGraphStart_descriptor = descriptor.getMessageTypes().get(5);
            eu_ostrzyciel_jelly_core_proto_v1_RdfGraphEnd_descriptor = descriptor.getMessageTypes().get(6);
            eu_ostrzyciel_jelly_core_proto_v1_RdfNamespaceDeclaration_descriptor = descriptor.getMessageTypes().get(7);
            eu_ostrzyciel_jelly_core_proto_v1_RdfNameEntry_descriptor = descriptor.getMessageTypes().get(8);
            eu_ostrzyciel_jelly_core_proto_v1_RdfPrefixEntry_descriptor = descriptor.getMessageTypes().get(9);
            eu_ostrzyciel_jelly_core_proto_v1_RdfDatatypeEntry_descriptor = descriptor.getMessageTypes().get(10);
            eu_ostrzyciel_jelly_core_proto_v1_RdfStreamOptions_descriptor = descriptor.getMessageTypes().get(11);
            eu_ostrzyciel_jelly_core_proto_v1_RdfStreamRow_descriptor = descriptor.getMessageTypes().get(12);
            eu_ostrzyciel_jelly_core_proto_v1_RdfStreamFrame_descriptor = descriptor.getMessageTypes().get(13);
            eu_ostrzyciel_jelly_core_proto_v1_RdfStreamFrame_MetadataEntry_descriptor =
                eu_ostrzyciel_jelly_core_proto_v1_RdfStreamFrame_descriptor.getNestedTypes().get(0);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * @return this proto file's descriptor.
     */
    public static Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }
}
