// Code generated by protocol buffer compiler. Do not edit!
package eu.neverblink.jelly.core.proto.v1;

import com.google.protobuf.CodedInputStream;
import com.google.protobuf.CodedOutputStream;
import com.google.protobuf.InvalidProtocolBufferException;
import eu.neverblink.protoc.java.runtime.MessageFactory;
import eu.neverblink.protoc.java.runtime.ProtoMessage;

import java.io.IOException;
import java.io.InputStream;

/**
 * Protobuf type {@code RdfDatatypeEntry}
 */
@SuppressWarnings("hiding")
public final class RdfDatatypeEntry extends ProtoMessage<RdfDatatypeEntry> implements Cloneable {
  /**
   * <code>optional uint32 id = 1;</code>
   */
  private int id;

  /**
   * <code>optional string value = 2;</code>
   */
  private String value_ = "";

  private RdfDatatypeEntry() {
  }

  /**
   * @return a new empty instance of {@code RdfDatatypeEntry}
   */
  public static RdfDatatypeEntry newInstance() {
    return new RdfDatatypeEntry();
  }

  /**
   * <code>optional uint32 id = 1;</code>
   * @return this
   */
  public RdfDatatypeEntry clearId() {
    id = 0;
    return this;
  }

  /**
   * <code>optional uint32 id = 1;</code>
   * @return the id
   */
  public int getId() {
    return id;
  }

  /**
   * <code>optional uint32 id = 1;</code>
   * @param value the id to set
   * @return this
   */
  public RdfDatatypeEntry setId(final int value) {
    id = value;
    return this;
  }

  /**
   * <code>optional string value = 2;</code>
   * @return this
   */
  public RdfDatatypeEntry clearValue() {
    value_ = "";
    return this;
  }

  /**
   * <code>optional string value = 2;</code>
   * @return the value_
   */
  public String getValue() {
    return value_;
  }

  /**
   * <code>optional string value = 2;</code>
   * @param value the value_ to set
   * @return this
   */
  public RdfDatatypeEntry setValue(final String value) {
    value_ = value;
    return this;
  }

  @Override
  public RdfDatatypeEntry copyFrom(final RdfDatatypeEntry other) {
    cachedSize = other.cachedSize;
    id = other.id;
    value_ = other.value_;
    return this;
  }

  @Override
  public RdfDatatypeEntry mergeFrom(final RdfDatatypeEntry other) {
    cachedSize = -1;
    setId(other.id);
    value_ = other.value_;
    return this;
  }

  @Override
  public RdfDatatypeEntry clear() {
    cachedSize = -1;
    id = 0;
    value_ = "";
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (!(o instanceof RdfDatatypeEntry)) {
      return false;
    }
    RdfDatatypeEntry other = (RdfDatatypeEntry) o;
    return id == other.id
      && value_.equals(other.value_);
  }

  @Override
  public void writeTo(final CodedOutputStream output) throws IOException {
    if (id != 0) {
      output.writeRawByte((byte) 8);
      output.writeUInt32NoTag(id);
    }
    if (!value_.isEmpty()) {
      output.writeRawByte((byte) 18);
      output.writeStringNoTag(value_);
    }
  }

  @Override
  protected int computeSerializedSize() {
    int size = 0;
    if (id != 0) {
      size += 1 + CodedOutputStream.computeUInt32SizeNoTag(id);
    }
    if (!value_.isEmpty()) {
      size += 1 + CodedOutputStream.computeStringSizeNoTag(value_);
    }
    return size;
  }

  @Override
  @SuppressWarnings("fallthrough")
  public RdfDatatypeEntry mergeFrom(final CodedInputStream input) throws IOException {
    // Enabled Fall-Through Optimization (Quickbuf)
    int tag = input.readTag();
    while (true) {
      switch (tag) {
        case 8: {
          // id
          id = input.readUInt32();
          tag = input.readTag();
          if (tag != 18) {
            break;
          }
        }
        case 18: {
          // value_
          value_ = input.readStringRequireUtf8();
          tag = input.readTag();
          if (tag != 0) {
            break;
          }
        }
        case 0: {
          return this;
        }
        default: {
          if (!input.skipField(tag)) {
            return this;
          }
          tag = input.readTag();
          break;
        }
      }
    }
  }

  @Override
  public RdfDatatypeEntry clone() {
    return new RdfDatatypeEntry().copyFrom(this);
  }

  public static RdfDatatypeEntry parseFrom(final byte[] data) throws
      InvalidProtocolBufferException {
    return ProtoMessage.mergeFrom(new RdfDatatypeEntry(), data).checkInitialized();
  }

  public static RdfDatatypeEntry parseFrom(final CodedInputStream input) throws IOException {
    return ProtoMessage.mergeFrom(new RdfDatatypeEntry(), input).checkInitialized();
  }

  public static RdfDatatypeEntry parseDelimitedFrom(final InputStream input) throws IOException {
    return ProtoMessage.parseDelimitedFrom(input, RdfDatatypeEntry.getFactory());
  }

  /**
   * @return factory for creating RdfDatatypeEntry messages
   */
  public static MessageFactory<RdfDatatypeEntry> getFactory() {
    return RdfDatatypeEntryFactory.INSTANCE;
  }

  private enum RdfDatatypeEntryFactory implements MessageFactory<RdfDatatypeEntry> {
    INSTANCE;

    @Override
    public RdfDatatypeEntry create() {
      return RdfDatatypeEntry.newInstance();
    }
  }
}
