// Code generated by protocol buffer compiler. Do not edit!
package eu.neverblink.jelly.core.proto.v1;

import com.google.protobuf.CodedInputStream;
import com.google.protobuf.CodedOutputStream;
import com.google.protobuf.InvalidProtocolBufferException;
import eu.neverblink.protoc.java.runtime.LimitedCodedInputStream;
import eu.neverblink.protoc.java.runtime.MessageFactory;
import eu.neverblink.protoc.java.runtime.ProtoMessage;

import java.io.IOException;
import java.io.InputStream;

/**
 * Protobuf type {@code RdfGraphEnd}
 */
@SuppressWarnings("hiding")
public final class RdfGraphEnd extends ProtoMessage<RdfGraphEnd> implements Cloneable {
  private RdfGraphEnd() {
  }

  /**
   * @return a new empty instance of {@code RdfGraphEnd}
   */
  public static RdfGraphEnd newInstance() {
    return new RdfGraphEnd();
  }

  @Override
  public RdfGraphEnd copyFrom(final RdfGraphEnd other) {
    cachedSize = other.cachedSize;
    return this;
  }

  @Override
  public RdfGraphEnd mergeFrom(final RdfGraphEnd other) {
    cachedSize = -1;
    return this;
  }

  @Override
  public RdfGraphEnd clear() {
    cachedSize = -1;
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (!(o instanceof RdfGraphEnd)) {
      return false;
    }
    RdfGraphEnd other = (RdfGraphEnd) o;
    return true;
  }

  @Override
  public void writeTo(final CodedOutputStream output) throws IOException {
  }

  @Override
  protected int computeSerializedSize() {
    int size = 0;
    return size;
  }

  @Override
  @SuppressWarnings("fallthrough")
  public RdfGraphEnd mergeFrom(final LimitedCodedInputStream inputLimited) throws IOException {
    // Enabled Fall-Through Optimization (Quickbuf)
    final CodedInputStream input = inputLimited.in();
    int tag = input.readTag();
    while (true) {
      switch (tag) {
        case 0: {
          return this;
        }
        default: {
          if (!input.skipField(tag)) {
            return this;
          }
          tag = input.readTag();
          break;
        }
      }
    }
  }

  @Override
  public RdfGraphEnd clone() {
    return new RdfGraphEnd().copyFrom(this);
  }

  public static RdfGraphEnd parseFrom(final byte[] data) throws InvalidProtocolBufferException {
    return ProtoMessage.mergeFrom(new RdfGraphEnd(), data).checkInitialized();
  }

  public static RdfGraphEnd parseFrom(final LimitedCodedInputStream input) throws IOException {
    return ProtoMessage.mergeFrom(new RdfGraphEnd(), input).checkInitialized();
  }

  public static RdfGraphEnd parseDelimitedFrom(final InputStream input) throws IOException {
    return ProtoMessage.parseDelimitedFrom(input, RdfGraphEnd.getFactory());
  }

  /**
   * @return factory for creating RdfGraphEnd messages
   */
  public static MessageFactory<RdfGraphEnd> getFactory() {
    return RdfGraphEndFactory.INSTANCE;
  }

  private enum RdfGraphEndFactory implements MessageFactory<RdfGraphEnd> {
    INSTANCE;

    @Override
    public RdfGraphEnd create() {
      return RdfGraphEnd.newInstance();
    }
  }
}
