// Code generated by protocol buffer compiler. Do not edit!
package eu.neverblink.jelly.core.proto.v1;

import com.google.protobuf.CodedInputStream;
import com.google.protobuf.CodedOutputStream;
import com.google.protobuf.InvalidProtocolBufferException;
import eu.neverblink.jelly.core.internal.proto.GraphBase;
import eu.neverblink.protoc.java.runtime.LimitedCodedInputStream;
import eu.neverblink.protoc.java.runtime.MessageFactory;
import eu.neverblink.protoc.java.runtime.ProtoMessage;

import java.io.IOException;
import java.io.InputStream;

/**
 * Protobuf type {@code RdfGraphStart}
 */
@SuppressWarnings("hiding")
public final class RdfGraphStart extends ProtoMessage<RdfGraphStart> implements Cloneable, GraphBase {
  public static final byte G_IRI = 1;

  public static final byte G_BNODE = 2;

  public static final byte G_DEFAULT_GRAPH = 3;

  public static final byte G_LITERAL = 4;

  /**
   * <code>oneof graph { ... }</code>
   */
  private Object graph = null;

  private byte graphNumber = 0;

  private RdfGraphStart() {
  }

  /**
   * @return a new empty instance of {@code RdfGraphStart}
   */
  public static RdfGraphStart newInstance() {
    return new RdfGraphStart();
  }

  public boolean hasGraph() {
    return graphNumber != 0;
  }

  /**
   * Low-level setter for the <code>graph</code> oneof field.
   * Use with care, as it will not check the type of the value.
   */
  public RdfGraphStart setGraph(Object graph, byte number) {
    this.graph = graph;
    this.graphNumber = number;
    return this;
  }

  /**
   * Returns the <code>graph</code> oneof field.
   */
  public Object getGraph() {
    return graph;
  }

  /**
   * Returns the set field number of the <code>graph</code> oneof field.
   */
  public byte getGraphFieldNumber() {
    return graphNumber;
  }

  /**
   * Sets the <code>graph</code> oneof field to gIri.
   */
  public RdfGraphStart setGIri(RdfIri gIri) {
    this.graph = gIri;
    this.graphNumber = 1;
    return this;
  }

  /**
   * Returns the <code>graph</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public RdfIri getGIri() {
    return (RdfIri) graph;
  }

  /**
   * Checks if the <code>graph</code> oneof is set to gIri.
   */
  public boolean hasGIri() {
    return graphNumber == 1;
  }

  /**
   * Sets the <code>graph</code> oneof field to gBnode.
   */
  public RdfGraphStart setGBnode(String gBnode) {
    this.graph = gBnode;
    this.graphNumber = 2;
    return this;
  }

  /**
   * Returns the <code>graph</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public String getGBnode() {
    return (String) graph;
  }

  /**
   * Checks if the <code>graph</code> oneof is set to gBnode.
   */
  public boolean hasGBnode() {
    return graphNumber == 2;
  }

  /**
   * Sets the <code>graph</code> oneof field to gDefaultGraph.
   */
  public RdfGraphStart setGDefaultGraph(RdfDefaultGraph gDefaultGraph) {
    this.graph = gDefaultGraph;
    this.graphNumber = 3;
    return this;
  }

  /**
   * Returns the <code>graph</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public RdfDefaultGraph getGDefaultGraph() {
    return (RdfDefaultGraph) graph;
  }

  /**
   * Checks if the <code>graph</code> oneof is set to gDefaultGraph.
   */
  public boolean hasGDefaultGraph() {
    return graphNumber == 3;
  }

  /**
   * Sets the <code>graph</code> oneof field to gLiteral.
   */
  public RdfGraphStart setGLiteral(RdfLiteral gLiteral) {
    this.graph = gLiteral;
    this.graphNumber = 4;
    return this;
  }

  /**
   * Returns the <code>graph</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public RdfLiteral getGLiteral() {
    return (RdfLiteral) graph;
  }

  /**
   * Checks if the <code>graph</code> oneof is set to gLiteral.
   */
  public boolean hasGLiteral() {
    return graphNumber == 4;
  }

  @Override
  public RdfGraphStart copyFrom(final RdfGraphStart other) {
    cachedSize = other.cachedSize;
    this.graph = other.graph;
    this.graphNumber = other.graphNumber;
    return this;
  }

  @Override
  public RdfGraphStart mergeFrom(final RdfGraphStart other) {
    cachedSize = -1;
    this.graph = other.graph;
    this.graphNumber = other.graphNumber;
    return this;
  }

  @Override
  public RdfGraphStart clear() {
    cachedSize = -1;
    this.graph = null;
    this.graphNumber = 0;
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (!(o instanceof RdfGraphStart)) {
      return false;
    }
    RdfGraphStart other = (RdfGraphStart) o;
    return graphNumber == other.graphNumber && (graphNumber == 0 || graph.equals(other.graph));
  }

  @Override
  public void writeTo(final CodedOutputStream output) throws IOException {
    switch (graphNumber) {
      case 1: {
        final var gIri = getGIri();
        output.writeRawByte((byte) 10);
        output.writeUInt32NoTag(gIri.getCachedSize());
        gIri.writeTo(output);
        break;
      }
      case 2: {
        final var gBnode = getGBnode();
        output.writeRawByte((byte) 18);
        output.writeStringNoTag(gBnode);
        break;
      }
      case 3: {
        final var gDefaultGraph = getGDefaultGraph();
        output.writeRawByte((byte) 26);
        output.writeUInt32NoTag(gDefaultGraph.getCachedSize());
        gDefaultGraph.writeTo(output);
        break;
      }
      case 4: {
        final var gLiteral = getGLiteral();
        output.writeRawByte((byte) 34);
        output.writeUInt32NoTag(gLiteral.getCachedSize());
        gLiteral.writeTo(output);
        break;
      }
    }
  }

  @Override
  protected int computeSerializedSize() {
    int size = 0;
    switch (graphNumber) {
      case 1: {
        final var gIri = getGIri();
        final int dataSize = gIri.getSerializedSize();
        size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
        break;
      }
      case 2: {
        final var gBnode = getGBnode();
        size += 1 + CodedOutputStream.computeStringSizeNoTag(gBnode);
        break;
      }
      case 3: {
        final var gDefaultGraph = getGDefaultGraph();
        final int dataSize = gDefaultGraph.getSerializedSize();
        size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
        break;
      }
      case 4: {
        final var gLiteral = getGLiteral();
        final int dataSize = gLiteral.getSerializedSize();
        size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
        break;
      }
    }
    return size;
  }

  @Override
  @SuppressWarnings("fallthrough")
  public RdfGraphStart mergeFrom(final LimitedCodedInputStream inputLimited) throws IOException {
    // Enabled Fall-Through Optimization (Quickbuf)
    final CodedInputStream input = inputLimited.in();
    int tag = input.readTag();
    while (true) {
      switch (tag) {
        case 10: {
          // gIri
          final RdfIri gIri;
          if (graphNumber == 1) {
            gIri = getGIri();
          }
          else {
            gIri = RdfIri.newInstance();
            setGIri(gIri);
          }
          ProtoMessage.mergeDelimitedFrom(gIri, inputLimited);
          tag = input.readTag();
          if (tag != 18) {
            break;
          }
        }
        case 18: {
          // gBnode
          setGBnode(input.readStringRequireUtf8());
          tag = input.readTag();
          if (tag != 26) {
            break;
          }
        }
        case 26: {
          // gDefaultGraph
          final RdfDefaultGraph gDefaultGraph;
          if (graphNumber == 3) {
            gDefaultGraph = getGDefaultGraph();
          }
          else {
            gDefaultGraph = RdfDefaultGraph.newInstance();
            setGDefaultGraph(gDefaultGraph);
          }
          ProtoMessage.mergeDelimitedFrom(gDefaultGraph, inputLimited);
          tag = input.readTag();
          if (tag != 34) {
            break;
          }
        }
        case 34: {
          // gLiteral
          final RdfLiteral gLiteral;
          if (graphNumber == 4) {
            gLiteral = getGLiteral();
          }
          else {
            gLiteral = RdfLiteral.newInstance();
            setGLiteral(gLiteral);
          }
          ProtoMessage.mergeDelimitedFrom(gLiteral, inputLimited);
          tag = input.readTag();
          if (tag != 0) {
            break;
          }
        }
        case 0: {
          return this;
        }
        default: {
          if (!input.skipField(tag)) {
            return this;
          }
          tag = input.readTag();
          break;
        }
      }
    }
  }

  @Override
  public RdfGraphStart clone() {
    return new RdfGraphStart().copyFrom(this);
  }

  public static RdfGraphStart parseFrom(final byte[] data) throws InvalidProtocolBufferException {
    return ProtoMessage.mergeFrom(new RdfGraphStart(), data).checkInitialized();
  }

  public static RdfGraphStart parseFrom(final LimitedCodedInputStream input) throws IOException {
    return ProtoMessage.mergeFrom(new RdfGraphStart(), input).checkInitialized();
  }

  public static RdfGraphStart parseDelimitedFrom(final InputStream input) throws IOException {
    return ProtoMessage.parseDelimitedFrom(input, RdfGraphStart.getFactory());
  }

  /**
   * @return factory for creating RdfGraphStart messages
   */
  public static MessageFactory<RdfGraphStart> getFactory() {
    return RdfGraphStartFactory.INSTANCE;
  }

  private enum RdfGraphStartFactory implements MessageFactory<RdfGraphStart> {
    INSTANCE;

    @Override
    public RdfGraphStart create() {
      return RdfGraphStart.newInstance();
    }
  }
}
