// Code generated by NeverBlink protoc-java-fast. Do not edit!
package eu.neverblink.jelly.core.proto.v1;

import com.google.protobuf.CodedInputStream;
import com.google.protobuf.CodedOutputStream;
import com.google.protobuf.InvalidProtocolBufferException;
import eu.neverblink.protoc.java.runtime.LimitedCodedInputStream;
import eu.neverblink.protoc.java.runtime.MessageFactory;
import eu.neverblink.protoc.java.runtime.ProtoMessage;

import java.io.IOException;
import java.io.InputStream;

/**
 * Protobuf type {@code RdfNameEntry}
 */
@SuppressWarnings("hiding")
public final class RdfNameEntry extends ProtoMessage<RdfNameEntry> implements Cloneable {
  /**
   * <code>optional uint32 id = 1;</code>
   */
  private int id;

  /**
   * <code>optional string value = 2;</code>
   */
  private String value_ = "";

  private RdfNameEntry() {
  }

  /**
   * @return a new empty instance of {@code RdfNameEntry}
   */
  public static RdfNameEntry newInstance() {
    return new RdfNameEntry();
  }

  /**
   * <code>optional uint32 id = 1;</code>
   * @return the id
   */
  public int getId() {
    return id;
  }

  /**
   * <code>optional uint32 id = 1;</code>
   * @param value the id to set
   * @return this
   */
  public RdfNameEntry setId(final int value) {
    id = value;
    return this;
  }

  /**
   * <code>optional string value = 2;</code>
   * @return the value_
   */
  public String getValue() {
    return value_;
  }

  /**
   * <code>optional string value = 2;</code>
   * @param value the value_ to set
   * @return this
   */
  public RdfNameEntry setValue(final String value) {
    value_ = value;
    return this;
  }

  @Override
  public RdfNameEntry copyFrom(final RdfNameEntry other) {
    cachedSize = other.cachedSize;
    id = other.id;
    value_ = other.value_;
    return this;
  }

  @Override
  public RdfNameEntry mergeFrom(final RdfNameEntry other) {
    cachedSize = -1;
    setId(other.id);
    value_ = other.value_;
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (!(o instanceof RdfNameEntry)) {
      return false;
    }
    RdfNameEntry other = (RdfNameEntry) o;
    return id == other.id
      && value_.equals(other.value_);
  }

  @Override
  public void writeTo(final CodedOutputStream output) throws IOException {
    if (id != 0) {
      output.writeRawByte((byte) 8);
      output.writeUInt32NoTag(id);
    }
    if (!value_.isEmpty()) {
      output.writeRawByte((byte) 18);
      output.writeStringNoTag(value_);
    }
  }

  @Override
  protected int computeSerializedSize() {
    int size = 0;
    if (id != 0) {
      size += 1 + CodedOutputStream.computeUInt32SizeNoTag(id);
    }
    if (!value_.isEmpty()) {
      size += 1 + CodedOutputStream.computeStringSizeNoTag(value_);
    }
    return size;
  }

  @Override
  @SuppressWarnings("fallthrough")
  public RdfNameEntry mergeFrom(final LimitedCodedInputStream inputLimited) throws IOException {
    // Enabled Fall-Through Optimization
    final CodedInputStream input = inputLimited.in();
    int tag = input.readTag();
    while (true) {
      switch (tag) {
        case 8: {
          // id
          id = input.readUInt32();
          tag = input.readTag();
          if (tag != 18) {
            break;
          }
        }
        case 18: {
          // value_
          value_ = input.readStringRequireUtf8();
          tag = input.readTag();
          if (tag != 0) {
            break;
          }
        }
        case 0: {
          return this;
        }
        default: {
          if (!input.skipField(tag)) {
            return this;
          }
          tag = input.readTag();
          break;
        }
      }
    }
  }

  @Override
  public RdfNameEntry clone() {
    return new RdfNameEntry().copyFrom(this);
  }

  public static RdfNameEntry parseFrom(final byte[] data) throws InvalidProtocolBufferException {
    return ProtoMessage.mergeFrom(new RdfNameEntry(), data);
  }

  public static RdfNameEntry parseFrom(final LimitedCodedInputStream input) throws IOException {
    return ProtoMessage.mergeFrom(new RdfNameEntry(), input);
  }

  public static RdfNameEntry parseDelimitedFrom(final InputStream input) throws IOException {
    return ProtoMessage.parseDelimitedFrom(input, RdfNameEntry.getFactory());
  }

  /**
   * @return factory for creating RdfNameEntry messages
   */
  public static MessageFactory<RdfNameEntry> getFactory() {
    return RdfNameEntryFactory.INSTANCE;
  }

  private enum RdfNameEntryFactory implements MessageFactory<RdfNameEntry> {
    INSTANCE;

    @Override
    public RdfNameEntry create() {
      return RdfNameEntry.newInstance();
    }
  }
}
