// Code generated by NeverBlink protoc-java-fast. Do not edit!
package eu.neverblink.jelly.core.proto.v1;

import com.google.protobuf.CodedInputStream;
import com.google.protobuf.CodedOutputStream;
import com.google.protobuf.InvalidProtocolBufferException;
import eu.neverblink.jelly.core.internal.proto.SpoBase;
import eu.neverblink.protoc.java.runtime.LimitedCodedInputStream;
import eu.neverblink.protoc.java.runtime.MessageFactory;
import eu.neverblink.protoc.java.runtime.ProtoMessage;

import java.io.IOException;
import java.io.InputStream;

/**
 * Protobuf type {@code RdfTriple}
 */
@SuppressWarnings("hiding")
public final class RdfTriple extends ProtoMessage<RdfTriple> implements SpoBase, Cloneable {
  public static final byte S_IRI = 1;

  public static final byte S_BNODE = 2;

  public static final byte S_LITERAL = 3;

  public static final byte S_TRIPLE_TERM = 4;

  public static final byte P_IRI = 5;

  public static final byte P_BNODE = 6;

  public static final byte P_LITERAL = 7;

  public static final byte P_TRIPLE_TERM = 8;

  public static final byte O_IRI = 9;

  public static final byte O_BNODE = 10;

  public static final byte O_LITERAL = 11;

  public static final byte O_TRIPLE_TERM = 12;

  /**
   * <code>oneof subject { ... }</code>
   */
  private Object subject = null;

  private byte subjectNumber = 0;

  /**
   * <code>oneof predicate { ... }</code>
   */
  private Object predicate = null;

  private byte predicateNumber = 0;

  /**
   * <code>oneof object { ... }</code>
   */
  private Object object = null;

  private byte objectNumber = 0;

  private RdfTriple() {
  }

  /**
   * @return a new empty instance of {@code RdfTriple}
   */
  public static RdfTriple newInstance() {
    return new RdfTriple();
  }

  public boolean hasSubject() {
    return subjectNumber != 0;
  }

  /**
   * Low-level setter for the <code>subject</code> oneof field.
   * Use with care, as it will not check the type of the value.
   */
  public RdfTriple setSubject(Object subject, byte number) {
    this.subject = subject;
    this.subjectNumber = number;
    return this;
  }

  /**
   * Returns the <code>subject</code> oneof field.
   */
  public Object getSubject() {
    return subject;
  }

  /**
   * Returns the set field number of the <code>subject</code> oneof field.
   */
  public byte getSubjectFieldNumber() {
    return subjectNumber;
  }

  /**
   * Sets the <code>subject</code> oneof field to sIri.
   */
  public RdfTriple setSIri(RdfIri sIri) {
    this.subject = sIri;
    this.subjectNumber = 1;
    return this;
  }

  /**
   * Returns the <code>subject</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public RdfIri getSIri() {
    return (RdfIri) subject;
  }

  /**
   * Checks if the <code>subject</code> oneof is set to sIri.
   */
  public boolean hasSIri() {
    return subjectNumber == 1;
  }

  /**
   * Sets the <code>subject</code> oneof field to sBnode.
   */
  public RdfTriple setSBnode(String sBnode) {
    this.subject = sBnode;
    this.subjectNumber = 2;
    return this;
  }

  /**
   * Returns the <code>subject</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public String getSBnode() {
    return (String) subject;
  }

  /**
   * Checks if the <code>subject</code> oneof is set to sBnode.
   */
  public boolean hasSBnode() {
    return subjectNumber == 2;
  }

  /**
   * Sets the <code>subject</code> oneof field to sLiteral.
   */
  public RdfTriple setSLiteral(RdfLiteral sLiteral) {
    this.subject = sLiteral;
    this.subjectNumber = 3;
    return this;
  }

  /**
   * Returns the <code>subject</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public RdfLiteral getSLiteral() {
    return (RdfLiteral) subject;
  }

  /**
   * Checks if the <code>subject</code> oneof is set to sLiteral.
   */
  public boolean hasSLiteral() {
    return subjectNumber == 3;
  }

  /**
   * Sets the <code>subject</code> oneof field to sTripleTerm.
   */
  public RdfTriple setSTripleTerm(RdfTriple sTripleTerm) {
    this.subject = sTripleTerm;
    this.subjectNumber = 4;
    return this;
  }

  /**
   * Returns the <code>subject</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public RdfTriple getSTripleTerm() {
    return (RdfTriple) subject;
  }

  /**
   * Checks if the <code>subject</code> oneof is set to sTripleTerm.
   */
  public boolean hasSTripleTerm() {
    return subjectNumber == 4;
  }

  public boolean hasPredicate() {
    return predicateNumber != 0;
  }

  /**
   * Low-level setter for the <code>predicate</code> oneof field.
   * Use with care, as it will not check the type of the value.
   */
  public RdfTriple setPredicate(Object predicate, byte number) {
    this.predicate = predicate;
    this.predicateNumber = number;
    return this;
  }

  /**
   * Returns the <code>predicate</code> oneof field.
   */
  public Object getPredicate() {
    return predicate;
  }

  /**
   * Returns the set field number of the <code>predicate</code> oneof field.
   */
  public byte getPredicateFieldNumber() {
    return predicateNumber;
  }

  /**
   * Sets the <code>predicate</code> oneof field to pIri.
   */
  public RdfTriple setPIri(RdfIri pIri) {
    this.predicate = pIri;
    this.predicateNumber = 5;
    return this;
  }

  /**
   * Returns the <code>predicate</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public RdfIri getPIri() {
    return (RdfIri) predicate;
  }

  /**
   * Checks if the <code>predicate</code> oneof is set to pIri.
   */
  public boolean hasPIri() {
    return predicateNumber == 5;
  }

  /**
   * Sets the <code>predicate</code> oneof field to pBnode.
   */
  public RdfTriple setPBnode(String pBnode) {
    this.predicate = pBnode;
    this.predicateNumber = 6;
    return this;
  }

  /**
   * Returns the <code>predicate</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public String getPBnode() {
    return (String) predicate;
  }

  /**
   * Checks if the <code>predicate</code> oneof is set to pBnode.
   */
  public boolean hasPBnode() {
    return predicateNumber == 6;
  }

  /**
   * Sets the <code>predicate</code> oneof field to pLiteral.
   */
  public RdfTriple setPLiteral(RdfLiteral pLiteral) {
    this.predicate = pLiteral;
    this.predicateNumber = 7;
    return this;
  }

  /**
   * Returns the <code>predicate</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public RdfLiteral getPLiteral() {
    return (RdfLiteral) predicate;
  }

  /**
   * Checks if the <code>predicate</code> oneof is set to pLiteral.
   */
  public boolean hasPLiteral() {
    return predicateNumber == 7;
  }

  /**
   * Sets the <code>predicate</code> oneof field to pTripleTerm.
   */
  public RdfTriple setPTripleTerm(RdfTriple pTripleTerm) {
    this.predicate = pTripleTerm;
    this.predicateNumber = 8;
    return this;
  }

  /**
   * Returns the <code>predicate</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public RdfTriple getPTripleTerm() {
    return (RdfTriple) predicate;
  }

  /**
   * Checks if the <code>predicate</code> oneof is set to pTripleTerm.
   */
  public boolean hasPTripleTerm() {
    return predicateNumber == 8;
  }

  public boolean hasObject() {
    return objectNumber != 0;
  }

  /**
   * Low-level setter for the <code>object</code> oneof field.
   * Use with care, as it will not check the type of the value.
   */
  public RdfTriple setObject(Object object, byte number) {
    this.object = object;
    this.objectNumber = number;
    return this;
  }

  /**
   * Returns the <code>object</code> oneof field.
   */
  public Object getObject() {
    return object;
  }

  /**
   * Returns the set field number of the <code>object</code> oneof field.
   */
  public byte getObjectFieldNumber() {
    return objectNumber;
  }

  /**
   * Sets the <code>object</code> oneof field to oIri.
   */
  public RdfTriple setOIri(RdfIri oIri) {
    this.object = oIri;
    this.objectNumber = 9;
    return this;
  }

  /**
   * Returns the <code>object</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public RdfIri getOIri() {
    return (RdfIri) object;
  }

  /**
   * Checks if the <code>object</code> oneof is set to oIri.
   */
  public boolean hasOIri() {
    return objectNumber == 9;
  }

  /**
   * Sets the <code>object</code> oneof field to oBnode.
   */
  public RdfTriple setOBnode(String oBnode) {
    this.object = oBnode;
    this.objectNumber = 10;
    return this;
  }

  /**
   * Returns the <code>object</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public String getOBnode() {
    return (String) object;
  }

  /**
   * Checks if the <code>object</code> oneof is set to oBnode.
   */
  public boolean hasOBnode() {
    return objectNumber == 10;
  }

  /**
   * Sets the <code>object</code> oneof field to oLiteral.
   */
  public RdfTriple setOLiteral(RdfLiteral oLiteral) {
    this.object = oLiteral;
    this.objectNumber = 11;
    return this;
  }

  /**
   * Returns the <code>object</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public RdfLiteral getOLiteral() {
    return (RdfLiteral) object;
  }

  /**
   * Checks if the <code>object</code> oneof is set to oLiteral.
   */
  public boolean hasOLiteral() {
    return objectNumber == 11;
  }

  /**
   * Sets the <code>object</code> oneof field to oTripleTerm.
   */
  public RdfTriple setOTripleTerm(RdfTriple oTripleTerm) {
    this.object = oTripleTerm;
    this.objectNumber = 12;
    return this;
  }

  /**
   * Returns the <code>object</code> oneof field.
   * Use with care, as it will not check if the correct field number is actually set.
   */
  public RdfTriple getOTripleTerm() {
    return (RdfTriple) object;
  }

  /**
   * Checks if the <code>object</code> oneof is set to oTripleTerm.
   */
  public boolean hasOTripleTerm() {
    return objectNumber == 12;
  }

  @Override
  public RdfTriple copyFrom(final RdfTriple other) {
    cachedSize = other.cachedSize;
    this.subject = other.subject;
    this.subjectNumber = other.subjectNumber;
    this.predicate = other.predicate;
    this.predicateNumber = other.predicateNumber;
    this.object = other.object;
    this.objectNumber = other.objectNumber;
    return this;
  }

  @Override
  public RdfTriple mergeFrom(final RdfTriple other) {
    cachedSize = -1;
    this.subject = other.subject;
    this.subjectNumber = other.subjectNumber;
    this.predicate = other.predicate;
    this.predicateNumber = other.predicateNumber;
    this.object = other.object;
    this.objectNumber = other.objectNumber;
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (!(o instanceof RdfTriple)) {
      return false;
    }
    RdfTriple other = (RdfTriple) o;
    return subjectNumber == other.subjectNumber && (subjectNumber == 0 || subject.equals(other.subject))
      && predicateNumber == other.predicateNumber && (predicateNumber == 0 || predicate.equals(other.predicate))
      && objectNumber == other.objectNumber && (objectNumber == 0 || object.equals(other.object));
  }

  @Override
  public void writeTo(final CodedOutputStream output) throws IOException {
    switch (subjectNumber) {
      case 1: {
        final var sIri = getSIri();
        output.writeRawByte((byte) 10);
        output.writeUInt32NoTag(sIri.getCachedSize());
        sIri.writeTo(output);
        break;
      }
      case 2: {
        final var sBnode = getSBnode();
        output.writeRawByte((byte) 18);
        output.writeStringNoTag(sBnode);
        break;
      }
      case 3: {
        final var sLiteral = getSLiteral();
        output.writeRawByte((byte) 26);
        output.writeUInt32NoTag(sLiteral.getCachedSize());
        sLiteral.writeTo(output);
        break;
      }
      case 4: {
        final var sTripleTerm = getSTripleTerm();
        output.writeRawByte((byte) 34);
        output.writeUInt32NoTag(sTripleTerm.getCachedSize());
        sTripleTerm.writeTo(output);
        break;
      }
    }
    switch (predicateNumber) {
      case 5: {
        final var pIri = getPIri();
        output.writeRawByte((byte) 42);
        output.writeUInt32NoTag(pIri.getCachedSize());
        pIri.writeTo(output);
        break;
      }
      case 6: {
        final var pBnode = getPBnode();
        output.writeRawByte((byte) 50);
        output.writeStringNoTag(pBnode);
        break;
      }
      case 7: {
        final var pLiteral = getPLiteral();
        output.writeRawByte((byte) 58);
        output.writeUInt32NoTag(pLiteral.getCachedSize());
        pLiteral.writeTo(output);
        break;
      }
      case 8: {
        final var pTripleTerm = getPTripleTerm();
        output.writeRawByte((byte) 66);
        output.writeUInt32NoTag(pTripleTerm.getCachedSize());
        pTripleTerm.writeTo(output);
        break;
      }
    }
    switch (objectNumber) {
      case 9: {
        final var oIri = getOIri();
        output.writeRawByte((byte) 74);
        output.writeUInt32NoTag(oIri.getCachedSize());
        oIri.writeTo(output);
        break;
      }
      case 10: {
        final var oBnode = getOBnode();
        output.writeRawByte((byte) 82);
        output.writeStringNoTag(oBnode);
        break;
      }
      case 11: {
        final var oLiteral = getOLiteral();
        output.writeRawByte((byte) 90);
        output.writeUInt32NoTag(oLiteral.getCachedSize());
        oLiteral.writeTo(output);
        break;
      }
      case 12: {
        final var oTripleTerm = getOTripleTerm();
        output.writeRawByte((byte) 98);
        output.writeUInt32NoTag(oTripleTerm.getCachedSize());
        oTripleTerm.writeTo(output);
        break;
      }
    }
  }

  @Override
  protected int computeSerializedSize() {
    int size = 0;
    switch (subjectNumber) {
      case 1: {
        final var sIri = getSIri();
        final int dataSize = sIri.getSerializedSize();
        size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
        break;
      }
      case 2: {
        final var sBnode = getSBnode();
        size += 1 + CodedOutputStream.computeStringSizeNoTag(sBnode);
        break;
      }
      case 3: {
        final var sLiteral = getSLiteral();
        final int dataSize = sLiteral.getSerializedSize();
        size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
        break;
      }
      case 4: {
        final var sTripleTerm = getSTripleTerm();
        final int dataSize = sTripleTerm.getSerializedSize();
        size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
        break;
      }
    }
    switch (predicateNumber) {
      case 5: {
        final var pIri = getPIri();
        final int dataSize = pIri.getSerializedSize();
        size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
        break;
      }
      case 6: {
        final var pBnode = getPBnode();
        size += 1 + CodedOutputStream.computeStringSizeNoTag(pBnode);
        break;
      }
      case 7: {
        final var pLiteral = getPLiteral();
        final int dataSize = pLiteral.getSerializedSize();
        size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
        break;
      }
      case 8: {
        final var pTripleTerm = getPTripleTerm();
        final int dataSize = pTripleTerm.getSerializedSize();
        size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
        break;
      }
    }
    switch (objectNumber) {
      case 9: {
        final var oIri = getOIri();
        final int dataSize = oIri.getSerializedSize();
        size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
        break;
      }
      case 10: {
        final var oBnode = getOBnode();
        size += 1 + CodedOutputStream.computeStringSizeNoTag(oBnode);
        break;
      }
      case 11: {
        final var oLiteral = getOLiteral();
        final int dataSize = oLiteral.getSerializedSize();
        size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
        break;
      }
      case 12: {
        final var oTripleTerm = getOTripleTerm();
        final int dataSize = oTripleTerm.getSerializedSize();
        size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
        break;
      }
    }
    return size;
  }

  @Override
  @SuppressWarnings("fallthrough")
  public RdfTriple mergeFrom(final LimitedCodedInputStream inputLimited) throws IOException {
    // Enabled Fall-Through Optimization
    final CodedInputStream input = inputLimited.in();
    int tag = input.readTag();
    while (true) {
      switch (tag) {
        case 10: {
          // sIri
          final RdfIri sIri;
          if (subjectNumber == 1) {
            sIri = getSIri();
          }
          else {
            sIri = RdfIri.newInstance();
            setSIri(sIri);
          }
          ProtoMessage.mergeDelimitedFrom(sIri, inputLimited);
          tag = input.readTag();
          if (tag != 42) {
            break;
          }
        }
        case 42: {
          // pIri
          final RdfIri pIri;
          if (predicateNumber == 5) {
            pIri = getPIri();
          }
          else {
            pIri = RdfIri.newInstance();
            setPIri(pIri);
          }
          ProtoMessage.mergeDelimitedFrom(pIri, inputLimited);
          tag = input.readTag();
          if (tag != 74) {
            break;
          }
        }
        case 74: {
          // oIri
          final RdfIri oIri;
          if (objectNumber == 9) {
            oIri = getOIri();
          }
          else {
            oIri = RdfIri.newInstance();
            setOIri(oIri);
          }
          ProtoMessage.mergeDelimitedFrom(oIri, inputLimited);
          tag = input.readTag();
          if (tag != 18) {
            break;
          }
        }
        case 18: {
          // sBnode
          setSBnode(input.readStringRequireUtf8());
          tag = input.readTag();
          if (tag != 50) {
            break;
          }
        }
        case 50: {
          // pBnode
          setPBnode(input.readStringRequireUtf8());
          tag = input.readTag();
          if (tag != 82) {
            break;
          }
        }
        case 82: {
          // oBnode
          setOBnode(input.readStringRequireUtf8());
          tag = input.readTag();
          if (tag != 26) {
            break;
          }
        }
        case 26: {
          // sLiteral
          final RdfLiteral sLiteral;
          if (subjectNumber == 3) {
            sLiteral = getSLiteral();
          }
          else {
            sLiteral = RdfLiteral.newInstance();
            setSLiteral(sLiteral);
          }
          ProtoMessage.mergeDelimitedFrom(sLiteral, inputLimited);
          tag = input.readTag();
          if (tag != 58) {
            break;
          }
        }
        case 58: {
          // pLiteral
          final RdfLiteral pLiteral;
          if (predicateNumber == 7) {
            pLiteral = getPLiteral();
          }
          else {
            pLiteral = RdfLiteral.newInstance();
            setPLiteral(pLiteral);
          }
          ProtoMessage.mergeDelimitedFrom(pLiteral, inputLimited);
          tag = input.readTag();
          if (tag != 90) {
            break;
          }
        }
        case 90: {
          // oLiteral
          final RdfLiteral oLiteral;
          if (objectNumber == 11) {
            oLiteral = getOLiteral();
          }
          else {
            oLiteral = RdfLiteral.newInstance();
            setOLiteral(oLiteral);
          }
          ProtoMessage.mergeDelimitedFrom(oLiteral, inputLimited);
          tag = input.readTag();
          if (tag != 34) {
            break;
          }
        }
        case 34: {
          // sTripleTerm
          final RdfTriple sTripleTerm;
          if (subjectNumber == 4) {
            sTripleTerm = getSTripleTerm();
          }
          else {
            sTripleTerm = RdfTriple.newInstance();
            setSTripleTerm(sTripleTerm);
          }
          ProtoMessage.mergeDelimitedFrom(sTripleTerm, inputLimited);
          tag = input.readTag();
          if (tag != 66) {
            break;
          }
        }
        case 66: {
          // pTripleTerm
          final RdfTriple pTripleTerm;
          if (predicateNumber == 8) {
            pTripleTerm = getPTripleTerm();
          }
          else {
            pTripleTerm = RdfTriple.newInstance();
            setPTripleTerm(pTripleTerm);
          }
          ProtoMessage.mergeDelimitedFrom(pTripleTerm, inputLimited);
          tag = input.readTag();
          if (tag != 98) {
            break;
          }
        }
        case 98: {
          // oTripleTerm
          final RdfTriple oTripleTerm;
          if (objectNumber == 12) {
            oTripleTerm = getOTripleTerm();
          }
          else {
            oTripleTerm = RdfTriple.newInstance();
            setOTripleTerm(oTripleTerm);
          }
          ProtoMessage.mergeDelimitedFrom(oTripleTerm, inputLimited);
          tag = input.readTag();
          if (tag != 0) {
            break;
          }
        }
        case 0: {
          return this;
        }
        default: {
          if (!input.skipField(tag)) {
            return this;
          }
          tag = input.readTag();
          break;
        }
      }
    }
  }

  @Override
  public RdfTriple clone() {
    return new RdfTriple().copyFrom(this);
  }

  public static RdfTriple parseFrom(final byte[] data) throws InvalidProtocolBufferException {
    return ProtoMessage.mergeFrom(new RdfTriple(), data);
  }

  public static RdfTriple parseFrom(final LimitedCodedInputStream input) throws IOException {
    return ProtoMessage.mergeFrom(new RdfTriple(), input);
  }

  public static RdfTriple parseDelimitedFrom(final InputStream input) throws IOException {
    return ProtoMessage.parseDelimitedFrom(input, RdfTriple.getFactory());
  }

  /**
   * @return factory for creating RdfTriple messages
   */
  public static MessageFactory<RdfTriple> getFactory() {
    return RdfTripleFactory.INSTANCE;
  }

  private enum RdfTripleFactory implements MessageFactory<RdfTriple> {
    INSTANCE;

    @Override
    public RdfTriple create() {
      return RdfTriple.newInstance();
    }
  }
}
