site_name: Jelly-JVM
site_description: Jelly-JVM is a JVM (Scala) implementation of the Jelly RDF streaming protocol.
site_url: https://jelly-rdf.github.io/jelly-jvm/

plugins:
  - search
  - mike
  - macros
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/Jelly-RDF/jelly-jvm
repo_name: Jelly-RDF/jelly-jvm
edit_uri: edit/main/docs/docs/

theme:
  name: material
  custom_dir: overrides
  features:
    # Behave like an SPA
    - navigation.instant
    - navigation.instant.progress
    # Update anchors in the address bar
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

  logo: assets/jelly_white.png
  favicon: assets/jelly_color.png
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Jelly-RDF/jelly-jvm
      name: Jelly-JVM on GitHub

nav:
  - Home: 'index.md'
  - Getting started (Jena/RDF4J plugin): 'getting-started-plugins.md'
  - Getting started (app developers): 'getting-started-devs.md'
  - User guide:
    - Apache Jena integration: 'user/jena.md'
    - Apache Jena CLI tools: 'user/jena-cli.md'
    - RDF4J integration: 'user/rdf4j.md'
    - Titanium RDF API integration: 'user/titanium.md'
    - Reactive streaming: 'user/reactive.md'
    - gRPC: 'user/grpc.md'
    - Useful utilities: 'user/utilities.md'
    - Low-level usage: 'user/low-level.md'
    - Compatibility policy: 'user/compatibility.md'
  - Developer guide:
    - Releases: 'dev/releases.md'
    - Implementing Jelly for other libraries: 'dev/implementing.md'
  - Contributing: 'contributing.md'
  - Code of conduct: 'code_of_conduct.md'
  - Licensing and citation: 'licensing.md'
  - Back to main Jelly docs ↩: 'https://w3id.org/jelly/'
