// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package eu.neverblink.jelly.core.proto.v1

object GrpcProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    // eu.neverblink.jelly.core.proto.v1.Rdf
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]](
      eu.neverblink.jelly.core.proto.v1.RdfStreamSubscribe,
      eu.neverblink.jelly.core.proto.v1.RdfStreamReceived
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CgpncnBjLnByb3RvEiFldS5vc3RyenljaWVsLmplbGx5LmNvcmUucHJvdG8udjEaCXJkZi5wcm90byKvAQoSUmRmU3RyZWFtU
  3Vic2NyaWJlEiAKBXRvcGljGAEgASgJQgriPwcSBXRvcGljUgV0b3BpYxJ3ChFyZXF1ZXN0ZWRfb3B0aW9ucxgCIAEoCzIzLmV1L
  m9zdHJ6eWNpZWwuamVsbHkuY29yZS5wcm90by52MS5SZGZTdHJlYW1PcHRpb25zQhXiPxISEHJlcXVlc3RlZE9wdGlvbnNSEHJlc
  XVlc3RlZE9wdGlvbnMiEwoRUmRmU3RyZWFtUmVjZWl2ZWQyhwIKEFJkZlN0cmVhbVNlcnZpY2USegoMU3Vic2NyaWJlUmRmEjUuZ
  XUub3N0cnp5Y2llbC5qZWxseS5jb3JlLnByb3RvLnYxLlJkZlN0cmVhbVN1YnNjcmliZRoxLmV1Lm9zdHJ6eWNpZWwuamVsbHkuY
  29yZS5wcm90by52MS5SZGZTdHJlYW1GcmFtZTABEncKClB1Ymxpc2hSZGYSMS5ldS5vc3RyenljaWVsLmplbGx5LmNvcmUucHJvd
  G8udjEuUmRmU3RyZWFtRnJhbWUaNC5ldS5vc3RyenljaWVsLmplbGx5LmNvcmUucHJvdG8udjEuUmRmU3RyZWFtUmVjZWl2ZWQoA
  WIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      eu.neverblink.jelly.core.proto.v1.Rdf.getDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}