
// Generated by Pekko gRPC. DO NOT EDIT.
package eu.neverblink.jelly.core.proto.v1

import org.apache.pekko
import org.apache.pekko.actor.ClassicActorSystemProvider
import org.apache.pekko.grpc.{GrpcChannel, GrpcClientCloseException, GrpcClientSettings, PekkoGrpcGenerated}
import org.apache.pekko.grpc.internal.{NettyClientUtils, ScalaClientStreamingRequestBuilder, ScalaServerStreamingRequestBuilder}
import org.apache.pekko.grpc.scaladsl.{PekkoGrpcClient, SingleResponseRequestBuilder, StreamResponseRequestBuilder}

import scala.concurrent.ExecutionContext





@PekkoGrpcGenerated
trait RdfStreamServiceClientPowerApi {
  
  /**
   * Lower level "lifted" version of the method, giving access to request metadata etc.
   * prefer subscribeRdf(eu.neverblink.jelly.core.proto.v1.RdfStreamSubscribe) if possible.
   */
  
  def subscribeRdf(): StreamResponseRequestBuilder[eu.neverblink.jelly.core.proto.v1.RdfStreamSubscribe, eu.neverblink.jelly.core.proto.v1.RdfStreamFrame] = ???
  
  
  /**
   * Lower level "lifted" version of the method, giving access to request metadata etc.
   * prefer publishRdf(org.apache.pekko.stream.scaladsl.Source[eu.neverblink.jelly.core.proto.v1.RdfStreamFrame, org.apache.pekko.NotUsed]) if possible.
   */
  
  def publishRdf(): SingleResponseRequestBuilder[org.apache.pekko.stream.scaladsl.Source[eu.neverblink.jelly.core.proto.v1.RdfStreamFrame, org.apache.pekko.NotUsed], eu.neverblink.jelly.core.proto.v1.RdfStreamReceived] = ???
  
  

}
