// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package eu.neverblink.jelly.core.proto.v1

/** Acknowledgement of receiving a stream sent by the server to the client.
  */
@SerialVersionUID(0L)
final case class RdfStreamReceived(
    ) extends scalapb.GeneratedMessage {
    final override def serializedSize: _root_.scala.Int = 0
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
    }
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = throw new MatchError(__fieldNumber)
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = throw new MatchError(__field)
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: eu.neverblink.jelly.core.proto.v1.RdfStreamReceived.type = eu.neverblink.jelly.core.proto.v1.RdfStreamReceived
    // @@protoc_insertion_point(GeneratedMessage[eu.neverblink.jelly.core.proto.v1.RdfStreamReceived])
}

object RdfStreamReceived extends scalapb.GeneratedMessageCompanion[eu.neverblink.jelly.core.proto.v1.RdfStreamReceived] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[eu.neverblink.jelly.core.proto.v1.RdfStreamReceived] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): eu.neverblink.jelly.core.proto.v1.RdfStreamReceived = {
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case tag => _input__.skipField(tag)
      }
    }
    eu.neverblink.jelly.core.proto.v1.RdfStreamReceived(
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[eu.neverblink.jelly.core.proto.v1.RdfStreamReceived] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      eu.neverblink.jelly.core.proto.v1.RdfStreamReceived(
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = GrpcProto.javaDescriptor.getMessageTypes().get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = GrpcProto.scalaDescriptor.messages(1)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = eu.neverblink.jelly.core.proto.v1.RdfStreamReceived(
  )
  def of(
  ): _root_.eu.neverblink.jelly.core.proto.v1.RdfStreamReceived = _root_.eu.neverblink.jelly.core.proto.v1.RdfStreamReceived(
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[eu.neverblink.jelly.core.proto.v1.RdfStreamReceived])
}
