name: Lint

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run prettier
        run: npm run format:check

  scalafmt-lint:
    name: Scalafmt lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: jrouly/scalafmt-native-action@v4

  scalafix-lint:
    name: Scalafix lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - run: sbt 'scalafixAll --check'
