name: Test documentation compilation

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version-file: 'docs/.python-version'
          cache-dependency-path: 'docs/requirements.txt'
  
      - name: Install dependencies
        working-directory: ./docs
        run: pip install -r requirements.txt

      - name: Build documentation
        working-directory: ./docs
        run: |
          export TAG='main'
          mkdocs build -s

      - name: Check broken links
        working-directory: ./docs
        run: |
          # Need to start a server because linkchecker doesn't recurse into local dirs
          # And canonical links don't work correctly
          TAG='main' mkdocs serve &
          sleep 5
          linkchecker \
            --no-warning \
            --check-extern \
            --ignore "https://doi.org" \
            http://localhost:8000
          kill $!
